### ISSUE TITLE
Site title is not changed after switching the language

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#105]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

### URL
`https://penguin-stats.io/`

### Steps to reproduce
1. Switch the language which is different from the current one
2. Find that the site title keeps showing in the previous language

### What is expected?
N/A

### What is actually happening?
N/A

**Comment by liqiang622** [comment]
You can add the following statement to the switch language function
`document.title = this.$t('app.name');`
