### ISSUE TITLE
Perform check on fetch results

### ISSUE THREAD

**Issue by GalvinGao** [penguin-statistics/frontend-v2#108]
### What problem does this feature solve?
Sometimes due to configuration error the backend may respond with HTML (see the exact version where the error occurs and affects the result of the frontend: https://frontend-v2-ducuxy5qh.now.sh/ (note the content following `hookResolved`))

### What does the proposed API look like?
The new algorithm should perform basic check on the object - it should contain the data that will not break the app.

**Comment by AlvISsReimu** [comment]
Still need some updates:
Now if the user close the dialog, it will never show up twice. 
When ajax error occurs, we change the loading icon and "Now Loading" to an alert icon and “Failed to load resources”. Users can open this dialog again by clicking on it.

**Comment by GalvinGao** [comment]
> Still need some updates:
> Now if the user close the dialog, it will never show up twice.
> When ajax error occurs, we change the loading icon and "Now Loading" to an alert icon and “Failed to load resources”. Users can open this dialog again by clicking on it.

This specific request has been implemented ;)

**Comment by GalvinGao** [comment]
> ### What problem does this feature solve?
> Sometimes due to configuration error the backend may respond with HTML (see the exact version where the error occurs and affects the result of the frontend: https://frontend-v2-ducuxy5qh.now.sh/ (note the content following `hookResolved`))
> 
> ### What does the proposed API look like?
> The new algorithm should perform basic check on the object - it should contain the data that will not break the app.

This has been done with falling back when getting nested object values. Closing ;)
