### ISSUE TITLE
Item and stage name will be returning into new lines on small screen devices in statistic tables

### ISSUE THREAD

**Issue by GalvinGao** [penguin-statistics/frontend-v2#11]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36`

### URL
`https://penguin-stats-frontend.galvingao.now.sh/result/stage/main_1/main_01-05`

### Steps to reproduce
1. Navigate to the URL
2. Open DevTools of the browser
3. Resize the screen to let the width be smaller than `580px`
4. Observe the text on the item

### What is expected?
the text SHOULD NOT be returned into new lines

### What is actually happening?
the text OCCURS TO returns into new lines

---
It seems the width of the particular field is not high enough. Adjustment is needed on such attribute.

Screenshot on such behavior, notice the red-boxed area:
![image](https://user-images.githubusercontent.com/12567059/62642271-ec680e80-b977-11e9-8255-24760fce43f5.png)

**Comment by AlvISsReimu** [comment]
stage code also has this issue:
![image](https://user-images.githubusercontent.com/25188552/62988993-30856400-bdfb-11e9-856c-a9bf0d8758bb.png)
