### ISSUE TITLE
一个优化统计偏差的建议

### ISSUE THREAD

**Issue by Prurite** [penguin-statistics/frontend-v2#117]
如之前的issue https://github.com/penguin-statistics/frontend-v1/issues/25 所说，完全依靠玩家上报的准确性比较差，可否项目与一些玩家（氪佬/肝帝？）合作，让他们提供一个时间段内自己刷图时的所有掉落情况，加权补入数据库？只是一个自己的想法，在此与各位探讨一下

关于为什么会觉得有偏差： https://bbs.nga.cn/read.php?tid=17749128 上敢把 S4-6 放到刷糖的推荐关，而且我个人刷了10把掉率还不错（掉了2-3个，没有具体统计），与企鹅物流上的数据偏差过大。

**Comment by AlvISsReimu** [comment]
目前群里确实上传了一些“内部高可信度数据”，不过在权重设置上还有些调试工作要做。感谢建议！

**Comment by lucenli** [comment]
早期的fgo也有类似的网站，叫做fgo wiki
由于fgo游戏的特殊性，可以通过中间人攻击的方法获得掉落信息，当时在某些群内比较普及，因为作者得到大家信任，所以也就放心在用了。
以此确保了前期数据的真实性
我们能借鉴吗

**Comment by Prurite** [comment]
> 早期的fgo也有类似的网站，叫做fgo wiki
> 由于fgo游戏的特殊性，可以通过中间人攻击的方法获得掉落信息，当时在某些群内比较普及，因为作者得到大家信任，所以也就放心在用了。
> 以此确保了前期数据的真实性
> 我们能借鉴吗

方舟是可以抓包的， 之前也有人提过这样的建议，把企鹅物流做成一个app，实现自动统计掉落，游戏内一键规划，自动刷关，内嵌公招工具啥的（原网址忘了，有知道的可以贴一下）。

**Comment by lucenli** [comment]
> > 早期的fgo也有类似的网站，叫做fgo wiki
> > 由于fgo游戏的特殊性，可以通过中间人攻击的方法获得掉落信息，当时在某些群内比较普及，因为作者得到大家信任，所以也就放心在用了。
> > 以此确保了前期数据的真实性
> > 我们能借鉴吗
> 
> 方舟是可以抓包的， 之前也有人提过这样的建议，把企鹅物流做成一个app，实现自动统计掉落，游戏内一键规划，自动刷关，内嵌公招工具啥的（原网址忘了，有知道的可以贴一下）。

感谢回复！
这比我想的要远的多了，既然技术上可以实现，我觉得还挺好的，就是可能这里有一些是在危险的边缘上。。。。
希望我们的项目可以越做越好，因为后期fgowiki的数据真实性堪忧，最后疏于维护也就。。。。我很担心如果我们没有‘可靠’的数据来源，也会失去权威性

**Comment by Prurite** [comment]
> 感谢回复！
这比我想的要远的多了，既然技术上可以实现，我觉得还挺好的，就是可能这里有一些是在危险的边缘上。。。。
希望我们的项目可以越做越好，因为后期fgowiki的数据真实性堪忧，最后疏于维护也就。。。。我很担心如果我们没有‘可靠’的数据来源，也会失去权威性

毕竟你不给玩家点实用的功能为什么他们要去装一个可能会破坏安全性的app，是吧（毕竟涉及中间人攻击）

**Comment by lucenli** [comment]
> > 感谢回复！
> > 这比我想的要远的多了，既然技术上可以实现，我觉得还挺好的，就是可能这里有一些是在危险的边缘上。。。。
> > 希望我们的项目可以越做越好，因为后期fgowiki的数据真实性堪忧，最后疏于维护也就。。。。我很担心如果我们没有‘可靠’的数据来源，也会失去权威性
> 
> 毕竟你不给玩家点实用的功能为什么他们要去装一个可能会破坏安全性的app，是吧（毕竟涉及中间人攻击）

也是，当时是在一些国服秃子聚集的群内推广的，推动的原因是可以提前看掉落，以及抽卡的时候可以统计抽卡数据.....
还可以同步你的素材，方便规划

我们似乎没有看掉落这一说，但是后两者还是有的。
不知道我们现在有这方面开发的想法吗

**Comment by lucenli** [comment]
> > > > 感谢回复！
> > > > 这比我想的要远的多了，既然技术上可以实现，我觉得还挺好的，就是可能这里有一些是在危险的边缘上。。。。
> > > > 希望我们的项目可以越做越好，因为后期fgowiki的数据真实性堪忧，最后疏于维护也就。。。。我很担心如果我们没有‘可靠’的数据来源，也会失去权威性
> > > 
> > > 
> > > 毕竟你不给玩家点实用的功能为什么他们要去装一个可能会破坏安全性的app，是吧（毕竟涉及中间人攻击）
> > 
> > 
> > 也是，当时是在一些国服秃子聚集的群内推广的，推动的原因是可以提前看掉落，以及抽卡的时候可以统计抽卡数据.....
> > 还可以同步你的素材，方便规划
> > 我们似乎没有看掉落这一说，但是后两者还是有的。
> > 不知道我们现在有这方面开发的想法吗
> 
> 已经有两位博士做过基于MITM的上传器了：
> [https://github.com/DavidDiao/ArkReport](url)
> [https://github.com/otz/arknights-drop-sniffer](url)
> 
> 前者在NGA有相关帖子，不过因为安装操作较为繁琐，劝退了很多人…
> 
> 我个人态度较为保守，担心如果企鹅数据提供这样一个MITM的工具，有的用户在这之后用脚本作死，或者干了一些奇怪的事情导致封号，回头甩锅我们，这样就说不清道不明了。想想看“都是锅GO让我的号被田中封了”这种言论（

谢谢，我去试试看

**Comment by Blealtan** [comment]
是否可能通过截屏记录信息上传？技术上图像识别难度不大，交互的话做个悬浮窗让用户在结算页面点一下这样子

**Comment by Prurite** [comment]
> 
> 
> 是否可能通过截屏记录信息上传？技术上图像识别难度不大，交互的话做个悬浮窗让用户在结算页面点一下这样子

问题在于像 LS-4 这种一屏幕显示不完的？在现在活动期间有特殊掉落的情况下更是如此

**Comment by Blealtan** [comment]
> 
> 
> > 是否可能通过截屏记录信息上传？技术上图像识别难度不大，交互的话做个悬浮窗让用户在结算页面点一下这样子
> 
> 问题在于像 LS-4 这种一屏幕显示不完的？在现在活动期间有特殊掉落的情况下更是如此

嗯，这确实是个问题。。前几天在群里就有人指出来，然后想到了如果自动滑屏获取信息的话，变成按键精灵的受限版似乎更敏感一些，就想不到怎么搞了
