### ISSUE TITLE
关卡综合性理智收益计算

### ISSUE THREAD

**Issue by iceinjure** [penguin-statistics/frontend-v2#118]
请问是否可以增加功能：∑（各种掉落材料的消耗理智（除了家具）x掉落率）/关卡消耗理智
从而给出一个综合性的关卡性价比并且从高到低排序。

新人基本什么材料（甚至包括赤金和经验书）都缺，导致刷精二材料的时候任何副产物掉落对我来说都很有意义。哪怕是低级材料都可以拿来升级一些后抽到干员的技能。所以很希望能用综合性的理智收益来排序一下关卡。毕竟精二可以稍微慢一点但是理智真的是一点点都不想浪费。

**Comment by GalvinGao** [comment]
此功能已在 [ArkPlanner](https://penguin-stats.io/planner) 中实现～
