### ISSUE TITLE
Wrong theme result on Recall button

### ISSUE THREAD

**Issue by GalvinGao** [penguin-statistics/frontend-v2#119]
### Environment
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1`

### URL
`https://penguin-stats.io/report`

### Steps to reproduce
1. Input any drop data
2. Click submit
3. In the snackbar popped, the error can be observed

### What is expected?
The button should display appropriate theme color

### What is actually happening?
In the light theme the button is displaying a white background with a white text color.
![7403A9FF-0954-4A8E-8846-F3C01EAAC40E](https://user-images.githubusercontent.com/12567059/63630908-84d9e080-c652-11e9-98c5-4621be9dc4f1.png)

**Comment by Blealtan** [comment]
It seems the `v-btn` control at `src/views/Report.vue:163` lacks an attribute `color`; adding `color="primary"` should work. Gonna test it out.
