### ISSUE TITLE
Limitation bug

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#151]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36`

### URL
`https://penguin-stats.io/report`

### Steps to reproduce
If you only report one `30011` drop in `main_00-01`, it does NOT show warning. However, this drop record is invalid, because the quantity of `2001` must be 3~5 but you report no `2001`.

Another small issue:
![image](https://user-images.githubusercontent.com/25188552/64063465-5fe0f280-cba9-11e9-922e-5c8ef356b332.png)
If a number fails to pass the check of `notIncludes`, it will show itemId instead of the number.

### What is expected?
N/A

### What is actually happening?
What we should iterate is `itemQuantityBounds`, instead of all dropped items.

For example, when we meet `2001` in `itemQuantityBounds` of `main_00-01`, we find that it does not appear in the drop. Then we should set its quantity to 0 and check whether 0 is valid or not.

**Comment by ChaosNiku** [comment]
not only in the main stage but in the sk stage,the problem also exists

**Comment by AlvISsReimu** [comment]
> not only in the main stage but in the sk stage,the problem also exists

yeah this is a common issue across all stages

**Comment by GalvinGao** [comment]
fixed in 7628267d0ea82cd28278aa971cee74741c15ee73. closing.
