### ISSUE TITLE
活动无限池允许一次上报十连结果

### ISSUE THREAD

**Issue by burntpancake** [penguin-statistics/frontend-v2#153]
### What problem does this feature solve?
操作繁琐：大部分人在活动无限池都是一次攒齐400代币后抽取十连，但上报数据时却要上报十次，每次只上报一个物品。
上报结果易出错：相同的物品连在一起出现多个时，记性不好的人容易忘记上传到第几个。

### What does the proposed API look like?
建议提供一次上报十连结果的选项。

**Comment by AlvISsReimu** [comment]
这种扭蛋池的汇报跟别的掉落不太一样，因为模式就固定在这几十种，像现在直接套用之前真正有掉落的关卡的数据结构、前端显示方式的话，只能做到现在这样单次上传。

事实上这个十连汇报本质就是之前一直在咕的“批量上传”。在掉落审查以及一些内部设计方面，开发者团队还没有讨论出一个成熟的方案，因此暂时没有打算只给这一个“关卡”单独加上十连汇报的功能。（相对地，只允许单次上传，搞事成本会提高）

如有不便，敬请谅解。
