### ISSUE TITLE
个人数据有误

### ISSUE THREAD

**Issue by lucenli** [penguin-statistics/frontend-v2#154]
至今关于这个个人数据使用的体验都不是特别的好...
首先遇到过最初提交数据后，没有分配到个人id

然后是遇到过好几次，数据上传提示成功，但是到个人界面却没有记录进去

最后是今天刚刚遇到的这个问题
![image](https://user-images.githubusercontent.com/16946496/64126692-5510a280-cde1-11e9-8055-d21bfeb41294.png)

我想请问，这是和网络连接有关还是怎么回事呢？
谢谢！

**Comment by AlvISsReimu** [comment]
看起来跟网络连接状况不好有关…
1. 提交后由于还未收到response，header内的Set-Cookie没有把userID放到cookies内
2. 单击“个人”时会发送请求查询个人记录，由于请求时间过长导致没看到个人记录/仍然停留在全平台记录
您可以去浏览器开发者工具里看一下Network中，这两个请求的响应时间？

**Comment by lucenli** [comment]
![image](https://user-images.githubusercontent.com/16946496/64270488-2ffd6a80-cf6e-11e9-924a-f9be9e895551.png)
![image](https://user-images.githubusercontent.com/16946496/64270591-64712680-cf6e-11e9-8a3a-700e10776fb1.png)
![image](https://user-images.githubusercontent.com/16946496/64270603-69ce7100-cf6e-11e9-9630-5b1b3be20913.png)

不确定这样的图片是不是有帮助的

我们得服务器在国内还是国外呢请问

**Comment by AlvISsReimu** [comment]
服务器是在国外的。
我这边没法reproduce这个错误…有点神奇

**Comment by lucenli** [comment]
> 服务器是在国外的。
> 我这边没法reproduce这个错误…有点神奇

我这边是浙江电信。
我加入梯子黑名单再来试试，谢谢！

**Comment by lucenli** [comment]
> 服务器是在国外的。
> 我这边没法reproduce这个错误…有点神奇

这太让人沮丧了
尝试添加到黑名单
清除浏览器cookies，强制刷新后再登陆
还是不行

**Comment by ChaosNiku** [comment]
> > 服务器是在国外的。
> > 我这边没法reproduce这个错误…有点神奇
> 
> 这太让人沮丧了
> 尝试添加到黑名单
> 清除浏览器cookies，强制刷新后再登陆
> 还是不行

请问现在可以了吗

**Comment by GalvinGao** [comment]
此issue时间过旧。
为保证项目issue处理效率，此issue将被关闭。
若此问题重新出现，请提交新issue，谢谢合作
