### ISSUE TITLE
We can present more information about Character

### ISSUE THREAD

**Issue by IvanZ0111** [penguin-statistics/frontend-v2#156]
### What problem does this feature solve?
There will be more Character in the game. when I manage to conquer a new stage. I need to replace some Characters into new Characters, and the comparison of Character's properties will help me quickly find which one is the most effective.

### What does the proposed API look like?
every level and every Character should be included.

**Comment by GalvinGao** [comment]
Thanks for your comment! Unfortunately, after careful consideration we decided to not include the character information in Penguin Statistics for the following reasons:

- To include such information requires a lot of code effort to polish the feature to the acceptable level of user satisfaction
- There's already [plenty](https://gachasalt.github.io/ArkToolDemo/) [of](https://ark-nights.com/operator) [tools](https://aktools.graueneko.xyz/charmat) implements such feature which I think are quite good

This is not gonna be fixed.
