### ISSUE TITLE
开放掉落提交 api

### ISSUE THREAD

**Issue by Prurite** [penguin-statistics/frontend-v2#158]
### What problem does this feature solve?
脚本 https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper 已趋于成熟，目前已有测试中的掉落识别功能（在dev分支上），希望企鹅物流能提供 API 供脚本自动上传掉落结果。

### What does the proposed API look like?
企鹅物流提供一个 API 供脚本调用。

**Comment by GalvinGao** [comment]
生产环境的 API 文档已部署为 [Swagger UI](https://penguin-stats.io/PenguinStats/swagger/swagger-ui.html)，其中包含了 report 相关的 API

文档内还暂时没有详细说明 request body 的格式（我们尽快加上），请直接参考下方格式构建 request body

Request Body (`Content-Type: application/json`)
```
{
  "stageId": string,
  "drops": [
    {
      "itemId": string,
      "quantity": integer
    },
    ...
  ],
  "furnitureNum": integer,
  "source": string,
  "version": string
}
```

需要特别注意的是在 `source` 与 `version` 处需要分别标明**数据来源程序**及其**版本**以便标注数据；你可以用 `ArknightsAutoHelper` 与对应的 分支+版本号 来区分，用别的名字也行～
**⚠️ 请注意一旦使用了一个source名就不要更换了，要不然这边不好统计**
