### ISSUE TITLE
cdn 故障

### ISSUE THREAD

**Issue by Prurite** [penguin-statistics/frontend-v2#159]
如题，目测用于存放图片的 cdn 因为没有备案拉掉了企鹅物流的图片存储服务，导致所有素材的图片加载异常。

https://penguin-stats.cdn.iblueg.cn/logos/penguin_stats_logo_texas.png

![image](https://user-images.githubusercontent.com/44775584/65809961-4cd83700-e1d6-11e9-8f8a-e424e6bf6beb.png)

![image](https://user-images.githubusercontent.com/44775584/65809965-5c578000-e1d6-11e9-967d-84a0dd57b4ef.png)

**Comment by Strontium233** [comment]
谢谢提醒_(:з)∠)_
在修复了
