### ISSUE TITLE
顯示問題

### ISSUE THREAD

**Issue by cakvfcwz** [penguin-statistics/frontend-v2#171]
環境：Windows10 1809，Chrome 79.0.3945.88（正式版本） （64 位），100%大小
問題：材料圖標顯示不全
![TIM截图20191226183845](https://user-images.githubusercontent.com/3722623/71472704-fd25fd80-280e-11ea-88bf-d9bd14ca76c1.png)
![TIM截图20191226183858](https://user-images.githubusercontent.com/3722623/71472705-fd25fd80-280e-11ea-89b3-4a1859057d5b.png)

**Comment by GalvinGao** [comment]
我们正在着手解决此问题，将在近期恢复
感谢反馈

**Comment by Strontium233** [comment]
一般這種情況都是因為網站更新了spirit圖片
清理下browsing data應該能解決

**Comment by GalvinGao** [comment]
网站sprite image已更新，问题已修复。closed.
