### ISSUE TITLE
ap_supply_lt_010(应急理智小样) lose in limitations api

### ISSUE THREAD

**Issue by LittleNightmare** [penguin-statistics/frontend-v2#175]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36`

### URL
`https://penguin-stats.io/PenguinStats/api/limitations`

### Steps to reproduce
cannot find the limit of ap_supply_lt_010(应急理智小样) in your [API](https://penguin-stats.io/PenguinStats/api/limitations)

### What is expected?
get limit

### What is actually happening?
cannot find it.
so I cannot report the mission if drop ap_supply_lt_010(应急理智小样)

---
Besides, both amounts, the lower and upper amount of randomMaterial_1(罗德岛物资补给), are 1. Is this ok?

**Comment by Strontium233** [comment]
I would say for both items, you could have your local variable to manually set the bounds to [0,1]. I.e. lower bound as 0 and upper bound as 1.
