### ISSUE TITLE
Position to be clicked may be wrong on low performance device

### ISSUE THREAD

**Issue by WordlessEcho** [penguin-statistics/frontend-v2#176]
### Environment
`Mozilla/5.0 (Linux; Android 10; Nexus 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36`

### URL
`https://penguin-stats.io/report`

### Steps to reproduce
1. Scrolling the screen.
1. Click a target.

### What is expected?
Click and website response where I click.

### What is actually happening?
Website response as before scrolling.

**Comment by GalvinGao** [comment]
Do you mean that the website responds to the position where you clicked before you scroll it, rather than responding to the position after you scroll it? And may I ask that, what do you mean when you mention _position_?
您是指，在您滑动页面位置后点击网站元素时，网站元素所反馈的位置，是您滑动页面前的位置？
请问，您所指的「position」是？

**Comment by WordlessEcho** [comment]
> Do you mean that the website responds to the position where you clicked before you scroll it, rather than responding to the position after you scroll it?
Yes.
> And may I ask that, what do you mean when you mention *position*?
Yes.

I am not a native English speaker. Sorry.

**Comment by GalvinGao** [comment]
> > Do you mean that the website responds to the position where you clicked before you scroll it, rather than responding to the position after you scroll it?
> 
> Yes.
> 
> > And may I ask that, what do you mean when you mention _position_?
> 
> Yes.
> 
> I am not a native English speaker. Sorry.

That's totally fine. May I kindly ask that if you agree, please use Chinese as the main communication language between us? No insult, but I'm having some difficulty to understand your issue. Thanks.
问题不大～请原谅我冒昧的请求与无礼，但若您同意，我们可以使用中文进行交流？我不是很能理解您遇到的问题。谢谢理解。

**Comment by WordlessEcho** [comment]
那我就以中文继续了，毕竟我都英文真的不太行。
是这样，我发现我所拥有的两台设备上（Nexus 5和小米5S），选择选项或是掉落物时延迟很大，而且总是会错位。

**Comment by GalvinGao** [comment]
> 那我就以中文继续了，毕竟我都英文真的不太行。
> 是这样，我发现我所拥有的两台设备上（Nexus 5和小米5S），选择选项或是掉落物时延迟很大，而且总是会错位。

现在网站确实有一些已知的性能问题，可能会导致现在您描述的问题，我们现正在积极处理。
至于错位方面，请问是在不滑动页面（页面完全静止）的情况下也会发生嘛？如果是的，还烦请提供页面截图或录屏（建议打开“开发者选项”-“显示触摸位置”），以便我们解决问题

**Comment by WordlessEcho** [comment]
静止时不会，只有滑动时会
![2020_01_04_20_12_26](https://user-images.githubusercontent.com/12007025/71765459-f5add500-2f2f-11ea-98ba-8617a0e17516.gif)

**Comment by GalvinGao** [comment]
看了下录屏，这个issue应该是由于网页性能低下导致的判断错误，I will assign myself.
