### ISSUE TITLE
Remember user's selection on stage and item

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#184]
### What problem does this feature solve?
Users may switch between Statistic Results and Drop Report frequently. Every time they need to choose zone and stage or item, which is a little bit inconvenient.

### What does the proposed API look like?
In one session, we remember user's selection.

For example:
A user chooses zone 1 in Drop Report, then switches to Statistic Results (by stage) and chooses zone 2 stage 3, then switches to Statistic Results (by item) and chooses 30013. Now when the user goes into Drop Report again, we should not go to ```/result/stage``` because this user has chosen zone 1 before. We should show ```/result/stage/main_1``` instead. And when the user switches to Statistic Results (by stage), we should show the result of zone 2 stage 3 directly, and 30013 for Statistic Results (by item).

This only takes effect during this session. When the user starts a new session, nothing will be memorized.

Note that we should memory 3 separate user's selections:
- Zone and stage selection in Drop Report
- Zone and stage selection in Statistic Results (by stage)
- Item selection in Statistic Results (by item)

**Comment by GalvinGao** [comment]
Has been achieved by using more intuitive redirect buttons and hyperlinks. Feel free to reopen if the outcome is not desired ;)
