### ISSUE TITLE
Re-open GT levels

### ISSUE THREAD

**Issue by Prurite** [penguin-statistics/frontend-v2#188]
### What problem does this feature solve?
The Knights & Treasure event is currently on in global servers, please consider re-open those levels.

### What does the proposed API look like?
Re-open those levels.

**Comment by GalvinGao** [comment]
Greetings!
The feature of refining international server support and splitting data by time range is still under internal investigation and conversation about the technological difficulty, server load, and urginess of such features. Thanks for submitting this issue and we will give you a feedback once we've done the discussion. We cherish your comment and **will** consider such feature request. ;)
