### ISSUE TITLE
Fading of names of all items in stage page

### ISSUE THREAD

**Issue by Strontium233** [penguin-statistics/frontend-v2#196]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36`

### URL
`https://penguin-stats.io/result/stage`

### Steps to reproduce
Move the scrollbar when it is possible

### What is expected?
All item names should be shown on the page.

### What is actually happening?
Once the scrollbar is moved...
1. If the scroll bar is below half of the length, then item names would be shown only if I scroll down.
2. If the scroll bar is somewhere around half of the length, then item names would be shown perfectly.
3. If the scroll bar is over half of the length, then item names would be shown only if I scroll up.

**Comment by GalvinGao** [comment]
Fixed
