### ISSUE TITLE
Support PWA

### ISSUE THREAD

**Issue by GalvinGao** [penguin-statistics/frontend-v2#20]
### What problem does this feature solve?
PWA enables the user the ability to install the current site as a native app on their mobile devices.

### What does the proposed API look like?
The one can utilize:
- [Official Plugin](https://github.com/vuejs/vue-cli/tree/v3/packages/%40vue/cli-plugin-pwa)
- [Getting Started with PWA on Google Developer](https://developers.google.com/web/progressive-web-apps/)

**Comment by zhuoyang** [comment]
is this removed? I can no longer install as a native app on android

**Comment by GalvinGao** [comment]
> is this removed? I can no longer install as a native app on android

Hi! The PWA is still supported. Which browser and phone model are you using?

I can confirm that on OnePlus 7 Pro, Android 10, Chrome 81.0.4044.138 the PWA is working properly ;)

If the issue DO exist, feel free to open a new issue at [https://new-issue.penguin-stats.io](https://new-issue.penguin-stats.io)

**Comment by zhuoyang** [comment]
I have opened a new issue #332
