### ISSUE TITLE
Cater planner api for EN servers

### ISSUE THREAD

**Issue by heravynch** [penguin-statistics/frontend-v2#201]
### What problem does this feature solve?
Hello, I am using the fetchService of https://planner.penguin-stats.io/plan/, and I realize the route plan does not cater for EN server (including chapter 5 and so). Is it possible to add an optional variable in the request header, so the server will only return en-available stages?

### What does the proposed API look like?
{"owned":{"研磨石":10},"required":{"改量装置":10},"exp_demand":false,"extra_outc":false,"gold_demand":true}

become

{"owned":{"研磨石":10},"required":{"改量装置":10},"exp_demand":false,"extra_outc":false,"gold_demand":true; "isCN":false}
where "isCN" will determine the stages filter

**Comment by AlvISsReimu** [comment]
We are working on the improvement of ArkPlanner currently. Thanks for your suggestion!

**Comment by GalvinGao** [comment]
You can now use `exclude` to specify excluded stage codes. We are working on improving the Planner api to better suit the data structure (use stageId instead of Chinese name, use stageId instead of code in `exclude`).
