### ISSUE TITLE
上传撤销的实现

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#22]
### What problem does this feature solve?
允许用户撤销之前1次的汇报。

### What does the proposed API look like?
撤销按钮，可否移到“掉落汇报”页面本身上？用户可能会认为底部提示信息右侧的按钮是用来关闭提示，导致误撤销。

**Comment by GalvinGao** [comment]
如果做成dialog然后弹出确认感觉怎么样w
因为做到页面上感觉会不太好排版 + 也不是很直观

**Comment by AlvISsReimu** [comment]
> 如果做成dialog然后弹出确认感觉怎么样w
> 因为做到页面上感觉会不太好排版 + 也不是很直观

The functionality works well. But the design is not following previous discussion.
IMO, the button on the right side of every snackbar should only perform one action: closing the snackbar. If we put undo here, even though we use a dialog to give user a chance to double check, the experience is still not good enough.
Let's discussion a little bit on where we should put the "Undo" button. @GalvinGao @AsahiLuna

**Comment by GalvinGao** [comment]
I've forgotten our discussion when I tried to resolve this issue 😅; my bad, I think the previous discussion has the best result. I will implement the undo feature with the result of the previous discussion.

**Comment by AlvISsReimu** [comment]
According to @cyj5230 's great idea, we want to design it like this:
![image](https://user-images.githubusercontent.com/25188552/63496754-4e943980-c477-11e9-9b9d-7997e76f5578.png)
