### ISSUE TITLE
i18n的完善

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#23]
### What problem does this feature solve?
N/A

### What does the proposed API look like?
目前不需要翻译的：素材名、素材类别

**Comment by GalvinGao** [comment]
UPDATE FOR 晚上在群内的讨论结果：素材名及类别的i18n需要做，具体实现方式有
- 后端对每个itemObject都加上类似 `{name: {_i18n: {zh: "基础作战记录", en: "Basic combat recording"}}}` 的i18n结果，或
- 前端使用类似 `{zh: [{"2001": "基础作战记录"}, {"2002": "初级作战记录"}, ...], en: [{"2001": "Elementry combat record"}, {"2002": "Basic combat record"}, ...}]` 根据itemId进行Map

**Comment by AlvISsReimu** [comment]
> UPDATE FOR 晚上在群内的讨论结果：素材名及类别的i18n需要做，具体实现方式有
> 
> * 后端对每个itemObject都加上类似 `{name: {_i18n: {zh: "基础作战记录", en: "Basic combat record"}}}` 的i18n结果，或
> * 前端使用类似 `{zh: [{"2001": "基础作战记录"}, {"2002": "初级作战记录"}, ...], en: [{"2001": "Elementry combat record"}, {"2002": "Basic combat record"}, ...}]` 根据itemId进行Map

与提供日语翻译的朋友交流后，一致认为大家现在主要靠识图来判断item，有时也会凭借汉字。在国际服/日服出来前，倾向于保持素材名和类别不翻译。等开新服、官方的翻译确定后，我们可以采取这种设计进行i18n的实现。
