### ISSUE TITLE
Bug in Arkplanner

### ISSUE THREAD

**Issue by mingl0280** [penguin-statistics/frontend-v2#232]
Bug description: When using ArkPlanner to plan a large dozen of items, it sometimes will show a "0-round" operation. 
![图片](https://user-images.githubusercontent.com/3364434/76175163-d4a47300-6170-11ea-8d8a-fae9e95646ff.png)

Bug replicate: 
I lost the raw data I put into the sheet, but this looks like it happens when the other chapters cannot meet the required numbers by 0.1. 

Severity: Low

**Comment by GalvinGao** [comment]
This is a upstream bug from https://github.com/ycremar/ArkPlanner. They are currently working to fix this problem.

**Comment by GalvinGao** [comment]
This has been fixed.
