### ISSUE TITLE
手机端总是正在加载

### ISSUE THREAD

**Issue by Memoriaaa** [penguin-statistics/frontend-v2#235]
自从更新了加载页面之后，手机浏览器就永远停在加载进不去，电脑端正常。用的是夸克浏览器，换手机自带的也一样。虽然提示首次加载较慢，但等了十分钟还在转圈。

**Comment by GalvinGao** [comment]
啊呜，烦请问设备型号是什么呢？

**Comment by Memoriaaa** [comment]
> 啊呜，烦请问设备型号是什么呢？

谢谢，没问题了！我觉得我的手机在搞我，此前我在不同的日子多次尝试都没成功打开过，包括今天傍晚来这提issue之前。晚上收到邮件后想着回复型号前再试一试，就正常了...

**Comment by GalvinGao** [comment]
啊呜，哈哈哈哈尴尬了
还是麻烦您可以的话提供一下手机型号；我这边 OnePlus 7 Pro 用夸克浏览器复现失败了awa

**Comment by Memoriaaa** [comment]
> 啊呜，哈哈哈哈尴尬了
> 还是麻烦您可以的话提供一下手机型号；我这边 OnePlus 7 Pro 用夸克浏览器复现失败了awa

红米k20 pro， MIUI11.0.5稳定版
