### ISSUE TITLE
S4-1这类关卡不能提交掉落结果

### ISSUE THREAD

**Issue by hongleng** [penguin-statistics/frontend-v2#238]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36`

### URL
`https://penguin-stats.io/report/main_4/sub_04-1-1`

### Steps to reproduce
点进S4-1或4-10这类字符长度大于3的关卡(或者说不符合/[0-9]-[0-9]/)，随意点选材料，尝试提交

### What is expected?
鼠标放置于 提交 按钮上时，箭头应该变为手指向上，并可以提交

### What is actually happening?
鼠标放置于 提交 按钮上时，箭头维持不变，点击无效

**Comment by GalvinGao** [comment]
啊嘞；我这边 `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36` 复现不成功awa

**Comment by hongleng** [comment]
4-4啥的都没问题，但是S4-1~S4-10我随机挑选了一些，都有问题
鼠标图标截不了图，非常难受

**Comment by hongleng** [comment]
我随机挑了一些别的章节的图，所有S开头的都不行，不是S开头的就没问题

**Comment by hongleng** [comment]
我试了很多关卡， 1-1这类  [0-9]-[0-9]没有问题
2-10, 4-10, S2-1这类不符合上面规则的都不行，是不是哪里正则表达式的判断有问题啊

**Comment by GalvinGao** [comment]
草，复现成功；是因为一个关卡名的z-index在提交按钮之上了... 我尽快修复
