### ISSUE TITLE
“团队成员”页面内容改动

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#24]
### What problem does this feature solve?
N/A

### What does the proposed API look like?
页面更名为：贡献者
增加若干贡献者，修改贡献项目

**Comment by GalvinGao** [comment]
疑问：增加的贡献者都怎么写呢www

**Comment by AlvISsReimu** [comment]
> 疑问：增加的贡献者都详细是谁呢

提供日语翻译的dalao~
