### ISSUE TITLE
S4-1这类关卡的掉落提交还是有点小问题

### ISSUE THREAD

**Issue by hongleng** [penguin-statistics/frontend-v2#242]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36`

### URL
`https://penguin-stats.io/report/main_4/main_04-10`

### Steps to reproduce
点击蓝色提交按钮的右半边（准确地说是，除了左边那个半圆形以外的任意区域）
4-10问题也一样

### What is expected?
点击有效

### What is actually happening?
点击无效

---
紧急程度：非常低

**Comment by GalvinGao** [comment]
啊呜，这个的话事实上是和您上一个issue（#238）应该是一样的问题。repo中已经修复了，但是新版本还暂时未部署 (捂脸)
先close啦（

**Comment by hongleng** [comment]
哦哦哦这样啊 我还以为和原版有变化了（笑哭）

imgg <notifications@github.com> 于2020年3月24日周二 下午8:40写道：
