### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by Ericli0708** [penguin-statistics/frontend-v2#252]
Win10 火狐浏览器总是显示正在加载，查了控制台有以下输出。请修复。

已拦截载入自“https://penguin-stats.io/js/app.b01a483c.js”的模块，它使用了不允许的 MIME 类型（“text/html”）。
penguin-stats.io
integrity 属性中的 “sha384” 散列值没有一个符合子资源的内容。 penguin-stats.io
已拦截载入自“https://penguin-stats.io/js/chunk-vendors.10ad1676.js”的模块，它使用了不允许的 MIME 类型（“text/html”）。
penguin-stats.io
integrity 属性中的 “sha384” 散列值没有一个符合子资源的内容。

**Comment by GalvinGao** [comment]
呜，看起来像是缓存的问题；请尝试清理本地缓存后刷新尝试一下？

**Comment by Ericli0708** [comment]
清缓存没用，清cookie才行，这个很不方便，每次清cookie都要让我重新登录很多网站。不知道你们有没有什么解决的办法。

**Comment by GalvinGao** [comment]
emmm，这种情况确实不应该出现；我这里直接刷新也复现不成功；稍后我看看能不能通过加载旧版本后刷新网站前往新版本复现。
另外，理应来说，是不需要清理cookie，而只用清理网站的所有本地缓存数据（ServiceWorker，LocalStorage，CacheStorage数据）即可～

感谢反馈

**Comment by Ericli0708** [comment]
我试了，光清理缓存没有用，必须清cookie，麻烦你们查一下看看是出了什么问题。谢谢。

**Comment by Ericli0708** [comment]
而且这个问题应该几个月前也出现过一次，应该也是你们版本更新的时候出现的缓存/cookie问题。

**Comment by Ericli0708** [comment]
哎，同样的问题今天又出现了，又是要清理cookie以及缓存才能解决。

**Comment by GalvinGao** [comment]
你好；我们已经在尝试修复了，还请等待~

**Comment by AlvISsReimu** [comment]
This should have been fixed in the latest release:)
