### ISSUE TITLE
“版权信息”显示调整

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#26]
### What problem does this feature solve?
左下版权信息不明显，手机上点击后会直接跳转至cc页面从而无法看到tooltip。

### What does the proposed API look like?
可以把cc标志直接换为“版权信息”，然后tooltip内放版权文字和cc标志。手机上，点“版权信息后”先别跳转，tooltip内部链接点了之后再跳转到cc的页面。

**Comment by GalvinGao** [comment]
准备都统一为弹出dialog显示License正文，正文部分包括数据部分的CC协议、以及前端代码的MIT协议两部分，然后可以设计相应链接跳转到对应页面ww
