### ISSUE TITLE
刷图规划提示网络请求失败

### ISSUE THREAD

**Issue by jerry9742** [penguin-statistics/frontend-v2#264]
https://new-issue.penguin-stats.io/planner
刷图规划无法计算，显示网络请求失败。以及进入首页时弹出资源丢失提示。
[penguin-stats.io-1586224694801.log](https://github.com/penguin-statistics/frontend-v2/files/4441633/penguin-stats.io-1586224694801.log)
↑↑↑控制台错误日志，似乎和跨域有关↑↑↑
![QQ图片20200407100136](https://user-images.githubusercontent.com/45534500/78622083-c902b400-78b6-11ea-90f9-f2ffd2be9c73.png)

请求头：
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Connection: keep-alive
Content-Length: 142433
Content-Type: text/plain;charset=UTF-8
Host: sentry.io
Origin: https://penguin-stats.io
Referer: https://penguin-stats.io/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by GalvinGao** [comment]
感谢反馈~ 看了下log，发现您客户端这边发送到 `https://client.crisp.chat` 的请求也返回了 403；我怀疑是不是您本地开启了 HTTP 代理但用户名/密码输入错误了。
我们也二次确认了是否为我们这边 CDN 的问题，发现一切正常；还请您检查下本地网络环境~

PS: 报告 CORS 错误是由于 Pre-flight Request 也被 403、无法验证所请求资源的 CORS 策略，于是请求被 CORS 拦截了；我们也二次确认了源站与 CDN 的 CORS 配置，均无误~

**Comment by jerry9742** [comment]
@GalvinGao 很感谢您的解答，问题已解决。

我并没有运行任何代理软件或者转发服务，但最近访问网站时确实经常需要通过CDN的人机验证 。怀疑是访问CDN资源时同样出现了这种情况才403。

更换了网络运营商，问题已经解决。感谢解答。

**Comment by GalvinGao** [comment]
客气～
