### ISSUE TITLE
UI: v-expansion-panel bottom radius

### ISSUE THREAD

**Issue by martinwang2002** [penguin-statistics/frontend-v2#270]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36`

### URL
`https://penguin-stats.io/report`

### Steps to reproduce
last html dom element of v-expansion-panel in v-expansion-panels

A radius bottom expansion panel is expected, but the UI is a right corner.

### What is expected?
A radius expansion panel bottom
![image](https://user-images.githubusercontent.com/29770303/79875101-bb533f80-841b-11ea-96b2-a34b942bbe5e.png)

### What is actually happening?
A right expansion panel corner
![image](https://user-images.githubusercontent.com/29770303/79874991-9c54ad80-841b-11ea-98b8-19b6f76c4022.png)

---

on line 6237 in vuetify.css (same as vuetify.min.css)

.v-expansion-panels:not(.v-expansion-panels--accordion):not(.v-expansion-panels--tile) > .v-expansion-panel--next-active .v-expansion-panel-header {

  **border-bottom-left-radius: inherit;**

  **border-bottom-right-radius: inherit;**

}

But this css is gone in the production. I cannot find it in the `/dist/css/app.[hash].css` & `/dist/css/chunk-vendors.[hash].css`

**Comment by GalvinGao** [comment]
Fixed in upstream package upgrade (upgraded to `vuetify@2.2.15`, in 9637e1b8d8fd3360422c81ea2d9a88a05280e10c). Closing.
