### ISSUE TITLE
能否增加一个近期数据权重更高的统计结果？

### ISSUE THREAD

**Issue by pingplug** [penguin-statistics/frontend-v2#276]
### What problem does this feature solve?
大前提：关卡掉率会变

如果某关掉率降低，玩家会少刷，提交的数据就会变少，平均值变化不及时导致数据不准

### What does the proposed API look like?
提供几组加权的掉落概率，具体算法看实现难度

比如近10日平均，或者每日衰减90%等

概率的算法在网页中公开，提供切换算法的接口

**Comment by pingplug** [comment]
以DM6为例，企鹅物流上统计的掉落概率是69%，我在第一天刷的时候10把掉落了8个，虽然结果偏高但是该事件发生的概率也有22%

最近两天刷DM6的时候，连续出现10把掉落5个的情况（然后我就刷DM8去了），如果关卡掉落概率仍是69%，这一事件发生的概率只有11%，而且连续发生了两天

我98%的自信认为DM6的关卡概率发生了变化，而企鹅物流的统计未能及时反映这次变化

很明显可以看到，企鹅物流这两天DM6的数据量很少（远少于1000，而目前总样本量有2200多），如果没有一个近期样本权重更高的结果，将会误导很多依赖该数据的网站

**Comment by Einzithy-D** [comment]
计算概率变化时不应只看均值，需考虑方差。

请尝试给出样本量为10情况下，出货率的95%置信区间。并考察端点情况。
你会意识到这个问题很可能只是因为样本太小造成的...

**Comment by pingplug** [comment]
> 计算概率变化时不应只看均值，需考虑方差。
> 
> 请尝试给出样本量为10情况下，出货率的95%置信区间。并考察端点情况。
> 你会意识到这个问题很可能只是因为样本太小造成的...

方差确实有接近1.46，5次也只是1.3倍标准差

连续两天如此，也就是连续20把掉10个，已经低于1.8倍标准差了

那几天确实相当非，包括提交issue之后两天甚至出现10把掉四个的，那几天刷了大概40多把才掉了20个，非要算的话已经出了95%置信区间。最近几天好些了，感觉上掉落正常了。。。

要么明日方舟掉落是伪随机，要么就是有概率调整，要么就是我太非。
我怀疑概率的主要原因是两个月前出现过刷十几次6-11一个扭转醇都没掉的情况，我当时还在仓库确认了半天是不是真的一个都没掉。。。
总之现在我刷DM关时一旦遇到连续四把只掉一个的时候就换一关刷。。。

**Comment by Einzithy-D** [comment]
我说的方差只是你估计量的方差。你估计量为掉落率 p 值应该在 [0,1] 之间。
如果你得到 大于 1 的方差/标准差... 那我觉得你的计算大概哪里出了些什么问题

**Comment by pingplug** [comment]
> 我说的方差只是你估计量的方差。你估计量为掉落率 p 值应该在 [0,1] 之间。
> 如果你得到 大于 1 的方差/标准差... 那我觉得你的计算大概哪里出了些什么问题


好吧我理解错了，我以为是在理论概率69%的情况下刷10把掉落分布的标准差，那几天掉出95%区间是肯定的。。。
我实在是不清楚你想说的方差是哪个，要不你帮我算一下？
我现在也没有当时刷图的掉落数据，凭我的印象，真要估计的话应该稳定在50%，掉落基本上是0，1，1，0，0，1，0，1这样，随便取连续10把都是掉4-6个，5个的情况居多。。。
活动刚开始的那段时间我还在企鹅物流提交结果，我个人的概率是80%（37/46），这个概率也是明显偏高的，感觉概率不对之后我就没有再向企鹅物流提交数据了。。。
按照69%的概率46把的掉落数均值为31.74，标准差为3.13，也出了两个标准差的范围了。。。
----
现在再看企鹅物流，样本量在10000多，概率还在 69%，看来概率没变，只是我那几天由欧变非了。。。
当然不排除伪随机的可能，毕竟某两天欧出两个标准差，过两天又非出两个标准差，这个实在是让我不能接受。。。

**Comment by Einzithy-D** [comment]
[http://www.mit.edu/~6.s085/notes/lecture2.pdf]
请自行参考上述材料，计算区间并做假设检验……

**Comment by pingplug** [comment]
> [http://www.mit.edu/~6.s085/notes/lecture2.pdf]
> 请自行参考上述材料，计算区间并做假设检验……

80% (37/46)标准差0.06，概率估计为80%，69%已经在两倍标准差边上了
50% (15/30)标准差0.09，概率估计为50%，69%刚好在两倍标准差外
前几天相当欧，后几天相当非，单独看没什么，两件事连续发生就太过罕见了，这也是我敢认为概率变化的原因之一。

p.s.: 希望能以引用的形式告诉我回复的是哪一句，也希望能多看一眼我之前回复中的其他内容，毕竟我也算是花精力认真回复了，谢谢

**Comment by Einzithy-D** [comment]
> 80% (37/46)标准差0.06，概率估计为80%，69%已经在两倍标准差边上了
> 50% (15/30)标准差0.09，概率估计为50%，69%刚好在两倍标准差外
> 前几天相当欧，后几天相当非，单独看没什么，两件事连续发生就太过罕见了，这也是我敢认为概率变化的原因之一。
> 
> p.s.: 希望能以引用的形式告诉我回复的是哪一句，也希望能多看一眼我之前回复中的其他内容，毕竟我也算是花精力认真回复了，谢谢

嗯，这段计算没有错，我同意。

95%的置信区间说的是 P( 真实值 属于 区间 ）= 95%。参考上面lecture的figure 2.2，你很可能恰好拿到尾巴上那么几个红色的区间。

一个好的检测应该是确定某个样本量n（你这里分别用了46和30，实际上考虑到正态分布，这个最好大一点,e.g 100。你可以看到你的标准差是6%和9%，实际上挺大的...)，重复k次(你这里k=2太小了)，记录掉落数量m（你这分别是37和15）。

当k足够大的时候，应该有 95% 左右的区间会包含 69% 的这个值。

**Comment by Einzithy-D** [comment]
Mini-batch和异常值检测

---

假定同一关卡某物品单次掉落服从二项分布，记为

X_i \stackrel{i.i.d}{\sim} Bernoulli(p)

现在重复通过该关卡 n, 获得下列随机样本作为掉落结果

(X_1, X_2, ..., X_i, ..., X_n)

当样本数量 n 增大时，根据中心极限定理，我们有

\frac{ \bar{X} - p}{\sqrt{ p(1-p)/ n}} \stackrel{d}{\to} N(0,1)

记  \bar{X} = \frac{1}{n} \sum^n_{i=1} X_i = \hat{p} 为样本均值， p 为未知的二项分布参数，n 为样本量，N(0,1) 为标准正态分布。

当 p 未知时，样本方差 p(1-p) 为未知，可用由于 \hat{p} 为 p 的无偏估计量，可用 \bar{X} (1-\bar{X}) 替代，故此逼近可写成

\frac{ \bar{X} - p}{\sqrt{ \bar{X}(1-\bar{X})/ n}} \stackrel{d}{\to} N(0,1)

考虑 \alpha-水平的置信区间，我们有

\begin{eqnarray*}
&& P( |Z| \le  z_{\alpha/2}) = 1-\alpha \\ \\
&& P\left(\left| \frac{ \bar{X} - p}{\sqrt{ \bar{X}(1-\bar{X})/ n}} \right|\le z_{\alpha/2} \right) = 1- \alpha \\ \\
&& P\left( \bar{X} -  z_{\alpha/2} \sqrt{\frac{ \bar{X}(1-\bar{X})}{n}} \le p \le \bar{X} +z_{\alpha/2} \sqrt{\frac{ \bar{X}(1-\bar{X})}{n}}   \right)  = 1 - \alpha
\end{eqnarray*}

估我们有一个随机区间

\left[\bar{X} -  z_{\alpha/2} \sqrt{\frac{ \bar{X}(1-\bar{X})}{n}}, \bar{X} +z_{\alpha/2} \sqrt{\frac{ \bar{X}(1-\bar{X})}{n}} \right]

以  1 - \alpha  的概率包含真实值 p.



但注意到，以上结果均为“未观测到结果的理论值”。对于每一个观测到的随机样本  \bar{x} = \frac{1}{n}\sum^n_{i=1} x_i， 我们会拿到一个确定的区间 

\left[\bar{x} -  z_{\alpha/2} \sqrt{\frac{ \bar{x}(1-\bar{x})}{n}}, \bar{x} +z_{\alpha/2} \sqrt{\frac{ \bar{x}(1-\bar{x})}{n}} \right]

对于此确定性间，要么其包含 p [则包含 p 的概率为 1], 要么其不包含 p [则包含 p 的概率为 0 ].



 为了还原 1-\alpha 的包含真实值 p 的概率，我们需要引入重复试验的概念。假设我们观测到一系列随机样本:

\text{第 }1\text{ 次试验} : (x_{1,1}, ..., x_{1,n}), \text{样本均值} \bar{x}_1 \\
\text{第 }2\text{ 次试验} : (x_{2,1}, ..., x_{2,n}), \text{样本均值} \bar{x}_2 \\
... \\
\text{第 }k\text{ 次试验} : (x_{k,1}, ..., x_{k,n}), \text{样本均值} \bar{x}_k \\

并记

y_j = \begin{cases}
1 & \text{如果} p \in \left[\bar{x}_j -  z_{\alpha/2} \sqrt{\frac{ \bar{x}_j(1-\bar{x}_j)}{n}}, \bar{x}_j +z_{\alpha/2} \sqrt{\frac{ \bar{x}_j(1-\bar{x}_j)}{n}} \right] \\
0 & \text{如果} p \notin \left[\bar{x}_j -  z_{\alpha/2} \sqrt{\frac{ \bar{x}_j(1-\bar{x}_j)}{n}}, \bar{x}_j +z_{\alpha/2} \sqrt{\frac{ \bar{x}_j(1-\bar{x}_j)}{n}} \right] \\
\end{cases}

则我们会有 

\frac{1}{k} \sum^k_{j=1} y_j \to E[Y] = P\left( \bar{X} -  z_{\alpha/2} \sqrt{\frac{ \bar{X}(1-\bar{X})}{n}} \le p \le \bar{X} +z_{\alpha/2} \sqrt{\frac{ \bar{X}(1-\bar{X})}{n}}   \right)  = 1 - \alpha

所以通过引入 k 个样本量为 n 的 mini-batch。如果每个mini-batch均行为良好【满足X_i的独立同分布假设】。 那么最终结果会逼近一个 

\bar{X} = \hat{p} \stackrel{d}{\to} N\left( p, \frac{p(1-p)}{n}\right)

即经验分布（观测到的样本的分布） \bar{x}_1, ..., \bar{x}_k 依分布收敛为上述分布。



几个点：

- 注意到，随机区间长度为
  2z_{\alpha/2} \sqrt{\frac{ \bar{X}(1-\bar{X})}{n}} \to 2 z_{\alpha/2} \sqrt{\frac{ p(1-p)}{n}}
  每个mini-batch的 n 选择的越大，所有区间长度就越小
- 当最终结果不【好】的时候，
e.g. 经验分布不像正态分布 / 某些mini-batch有极端区间 / 区间覆盖率离 1-\alpha 差的很远
  极有可能为样本不满足独立同分布(i.i.d)假设，即：
  1. 不满足独立假设： 某一个batch的样本表现得像受某些特定因素控制；
可能是有意的搞事、可能是批量汇报、可能是只汇报了极欧/极非的情况。
  2. 不满足同分布假设：某件物品掉落概率在时间段 [t_0,t_1] 内为 p_1, ...,  在时间段[t_{i-1}, t_i] 为 p_i
可观测到区间中心值出现断层，可通过假设检验验证。

**Comment by pingplug** [comment]
个人的精力和财力终究是有限的，我整个活动DM6也只刷了300多把，更何况后面的数据我并没有统计。

>      一个好的检测应该是确定某个样本量n（你这里分别用了46和30，实际上考虑到正态分布，这个最好大一点,e.g 100。你可以看到你的标准差是6%和9%，实际上挺大的...)，重复k次(你这里k=2太小了)，记录掉落数量m（你这分别是37和15）。

- 企鹅物流有没有机制实现这样的检验？
- 如果没有的话有没有可能实现？
- 如果数据确实改变了（第六章的时候某些关卡掉落增加凝胶和炽合金，各材料的掉落必然有所调整）如何通过检测及时发现和调整？
- 如何检验概率是否是随时间、个人改变但总概率保持不变？

以上是我关于企鹅物流的疑问

**Comment by pingplug** [comment]
感觉有 #307 这个就不用开了
