### ISSUE TITLE
关于用户名显示的一些改进

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#28]
### What problem does this feature solve?
注销登录在手机上没法显示，因为点击后就直接注销了，很突然。

### What does the proposed API look like?
点用户名后出现dropdown，里面放一个选项“注销”？
另外希望增加旧版的对用户ID的说明。

**Comment by GalvinGao** [comment]
1. 将设计为点击用户ID后显示说明+退出登录按钮
2. 用户ID说明可于登录页面展示
