### ISSUE TITLE
专门给国际服，日服和韩服

### ISSUE THREAD

**Issue by Aquastic** [penguin-statistics/frontend-v2#282]
### What problem does this feature solve?
毕竟国服和其他服的差距挺大的，活动也不一样，所以我想能不能放一个按钮是专门给国际服，日服和韩服罢了。因为目前为止国服的DM关卡在其他服没有，而且其他服的活动也不一样。

### What does the proposed API look like?
就设定一个按钮是把国服的活动关卡移除，然后一个按钮是其他服的活动移除，这样的话他们可以不用担心其他服的活动干扰owo

**Comment by Aquastic** [comment]
指的“活动关卡移除”是指只是国服活动的移除让其他服不需烦DM关卡突然出现类似的问题。

**Comment by GalvinGao** [comment]
你好~ 我们计划在新的 `v3.0.0` 版本中添加对于不同上游游戏服务器的数据源切换支持，届时您所提出的 Feature 也将被支持 ;)
详细计划欢迎前往 [v3.0.0: Multi Upstream Server Support!](https://github.com/penguin-statistics/frontend-v2/projects/3) 查看
感谢支持 :heart:
