### ISSUE TITLE
Limitation Bug

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#29]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36`

### URL
`https://penguin-stats.io/report`

### Steps to reproduce
以4-10为例，在普通掉落里，增加一个蓝装置掉落。此时额外掉落里的蓝装置加号变暗，只有常规掉落里的能再添加。

### What is expected?
蓝装置范围是0~2，事实上是常规掉落里最大1个，额外里最大1个，但是在limitation里没有区分（也不准备区分，因为我们统计结果无视“常规、额外、罕见”）。
目前想出两种解决办法：
1. 增减掉落数时不设限制，汇报前检查limitation，有问题弹窗出提示（模仿旧版）
2. 之前的例子中，常规和额外的蓝装置的加号全都变为可用，意思是常规里2个蓝装置，或者1常规1额外都允许。

个人倾向第一种。

### What is actually happening?
N/A

**Comment by GalvinGao** [comment]
个人倾向第一种，理由如下：
 - 实现较第二种简单很多
 - 第二种需要考虑常规中2时，在额外中+1时的对应处理方式（如：常规直接自动-1（较好实现但不直观，用户可能注意不到改动而造成提交的数据不真实）；常规数量下方弹出错误提示（较难实现））

**Comment by AlvISsReimu** [comment]
> 个人倾向第一种，理由如下：
> 
> * 实现较第二种简单很多
> * 第二种需要考虑常规中2时，在额外中+1时的对应处理方式（如：常规直接自动-1（较好实现但不直观，用户可能注意不到改动而造成提交的数据不真实）；常规数量下方弹出错误提示（较难实现））

常规已经有2时，由于已经达到limitation中的上限所以额外中的加号是disabled的。

**Comment by GalvinGao** [comment]
> > 个人倾向第一种，理由如下：
> > 
> > * 实现较第二种简单很多
> > * 第二种需要考虑常规中2时，在额外中+1时的对应处理方式（如：常规直接自动-1（较好实现但不直观，用户可能注意不到改动而造成提交的数据不真实）；常规数量下方弹出错误提示（较难实现））
> 
> 常规已经有2时，由于已经达到limitation中的上限所以额外中的加号是disabled的。

- In src/views/Report.vue, change handleChange → handleChange([itemId, mutationType])
    - mutationType can only be→ ["add", "subtract"]
    - find the corresponding record using itemId in `this.results`, then add (item.quantity += 1) and vice versa.
    - When iterating every item, give it a "key" prop that will be used to **identify each of the items**
    - Use `this.results` to store original data, and `this.generate()` to generate the result that will be pushed to the server.
