### ISSUE TITLE
以后其他服的活动

### ISSUE THREAD

**Issue by Aquastic** [penguin-statistics/frontend-v2#295]
哈喽，我又来乱了XD（抱歉）。就我上次有提议把国服的活动去除掉，我想问问，如果其他服的活动关卡上线的话，想问问有没有可能把活动关卡放进里面呢。再次感到抱歉还有感谢你们对这个网站的付出。<3

**Comment by GalvinGao** [comment]
你好~ 我们计划在新的 `v3.0.0` 版本中添加对于不同上游游戏服务器的数据源切换支持，届时您所提出的 Feature 也将被支持 ;)
详细计划欢迎前往 [v3.0.0: Multi Upstream Server Support!](https://github.com/penguin-statistics/frontend-v2/projects/3) 查看
