### ISSUE TITLE
The background color make it hard to see the number

### ISSUE THREAD

**Issue by Ericli0708** [penguin-statistics/frontend-v2#298]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0`

### URL
`https://penguin-stats.io/report`

### Steps to reproduce
Episode 7, the number mix with the background because both of them are yellow. This happen at dark theme.

### What is expected?
Change the color or remove the background.

### What is actually happening?
The background color make it hard to see the number

**Comment by Ericli0708** [comment]
![图片](https://user-images.githubusercontent.com/33204722/81244893-2e78ca80-9046-11ea-9452-464032c7ffb7.png)

**Comment by GalvinGao** [comment]
Has been fixed in https://github.com/penguin-statistics/frontend-v2/commit/c2680d36a94bc018329bc8aeee7d78c870b7c7cf. Waiting for merge.
