### ISSUE TITLE
Report Drops by Screenshot Recognition | 截图识别上传

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#304]
一些已有的讨论：
要综合考虑识别效率、准确率。
是前端识别，上传掉落数据，还是前端压缩并上传图片，后端识别？用户可能担心流量问题。

**Comment by GalvinGao** [comment]
Proudly closing this issue as this feature has already been running smoothly for 9+ months (and why is this still left open lol).
