### ISSUE TITLE
Bulk Upload Drops | 批量上传掉落记录

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#305]
需要设计方便交互的UI。对批量的审核也要有所考虑，暂时可以只开放给内部？

**Comment by GalvinGao** [comment]
由于大量掉落关卡以及集中刷图的现象最近开始多了起来，批量上传有必要继续进行讨论。

下述几个实现批量上传前需要解决的问题：
1. 数据可信度：破坏成本大大降低。可行解决方案：批量上传对于一特定账号有频次限制，到限制之后仅可使用单次上传。在第三方登录开发完毕并引导用户绑定对应账户后，此解决方案才可能有效。
2. 时间分布：单次批量上传过多数据将会导致该段时间上传量非常大，一方面不利于后期数据分析，另一方面会对普通用户造成困惑。解决方案：可让用户自行输入刷图的起止时间，和刷图次数计算后服务端可对数据进行标记后均匀分布在所选时间段内。
3. 用户交互：批量上传用户交互将是一大难点。解决方案：在用户输入一次掉落的数据后，旁边显示该“掉落情况”与对应次数（此时为1），用户可通过直接加减对应次数方便地录入对应情况的次数。可大大减少相同pattern的录入时间和精力。

有可能还有更多问题，欢迎列出

**Comment by GalvinGao** [comment]
由于掉落组合的需要，批量上传将会导致掉落组合无法被统计。通过 #321 #367 及已经实现的批量截图识别功能，已能解决大部分需要批量上传的需求，因此关闭此议题。
