### ISSUE TITLE
Server Statistics | 全站数据一览

### ISSUE THREAD

**Issue by ChaosNiku** [penguin-statistics/frontend-v2#308]
1. 在部分页面上显示当前已使用用户总数，注册用户数，内部用户数等
2. 掉落查看页面，点击某关卡tab，显示这一关卡总上传用户量
+ 提升用户对掉落数据了解以及所有数据可靠度信赖
+

**Comment by GalvinGao** [comment]
内部规划了**全站数据一览**模块，排期于`v3.1.0`进行实现~
将实现以下 features（包括但不限于）：
- 全站已注册用户数
- 全站上传总数
- 热门上传关卡/物品
- 最近的上传量变化曲线

欢迎添加其他建议~

**Comment by ChaosNiku** [comment]
是否考虑添加
- 活跃用户数量（最近7天/3天/？天使用用户数）
- 目前正在使用用户数
- 不同服用户量
- 某次活动上传量最高关卡

**Comment by GalvinGao** [comment]
> * 活跃用户数量（最近7天/3天/？天使用用户数）
这个应该是没问题的～

> * 目前正在使用用户数
“正在使用的用户数” 具体是如何计算呢？主要是，“现在在线”这部分我们现在使用的是Google Analytics，GA那边并不支持外部api调用；而自己实现一个相关功能，通常会带来一些不必要的服务器负载（如，我们需要记录每个ip对网页的访问，若此ip在两小时内无再次刷新则判断已经离线）。个人觉得这个可以先不实现？

> * 不同服用户量
用户的话，是多服共用账号的，一个账号可以上传多个服务器的数据

> * 某次活动上传量最高关卡
这个也不错；可以和“上传量TOP10关卡排名”做在差不多一起的位置

**Comment by martinwang2002** [comment]
@GalvinGao 
> > * 目前正在使用用户数
> 
> “正在使用的用户数” 具体是如何计算呢？主要是，“现在在线”这部分我们现在使用的是Google Analytics，GA那边并不支持外部api调用；而自己实现一个相关功能，通常会带来一些不必要的服务器负载（如，我们需要记录每个ip对网页的访问，若此ip在两小时内无再次刷新则判断已经离线）。个人觉得这个可以先不实现？

GA has APIs.
[DevGuides](https://developers.google.com/analytics/devguides/reporting/core/v4)
[Metrics](https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/)
[Query explorer](https://ga-dev-tools.appspot.com/query-explorer/)

In the metrics, there is `ga:sessions`, `ga:1dayUsers`, `ga:14daysUsers`, `ga:14daysUsers`.
If possible, GA can set user id which can analyze user behaviors better in `v3.0.0`.

For Cloudflare which the `penguin-statistics.io` uses, there is an [API](https://api.cloudflare.com/#zone-analytics-dashboard) which can load unique ips (and other CDN information) over a period of time which can be used to track online users.
However, I do not know whether there is an API for the CDN server of `penguin-statistics.cn`

**Comment by ChaosNiku** [comment]
> > * 目前正在使用用户数
> 
> “正在使用的用户数” 具体是如何计算呢？主要是，“现在在线”这部分我们现在使用的是Google Analytics，GA那边并不支持外部api调用；而自己实现一个相关功能，通常会带来一些不必要的服务器负载（如，我们需要记录每个ip对网页的访问，若此ip在两小时内无再次刷新则判断已经离线）。个人觉得这个可以先不实现？
> 这个想的时候只是个optional功能，当初构思的实现跟g桑思路差不多，我也觉得可以暂时搁置
> > * 不同服用户量
> 
> 用户的话，是多服共用账号的，一个账号可以上传多个服务器的数据
> 那可以考虑不同服上传量对比？比如小马活动各个服上传量分别是多少（考虑单独开一个页面？）
> > * 某次活动上传量最高关卡
> 
> 这个也不错；可以和“上传量TOP10关卡排名”做在差不多一起的位置

- 捐赠用户量捐赠名单（放到致谢页面？）

**Comment by GalvinGao** [comment]
> > > * 目前正在使用用户数
> > 
> > 
> > “正在使用的用户数” 具体是如何计算呢？主要是，“现在在线”这部分我们现在使用的是Google Analytics，GA那边并不支持外部api调用；而自己实现一个相关功能，通常会带来一些不必要的服务器负载（如，我们需要记录每个ip对网页的访问，若此ip在两小时内无再次刷新则判断已经离线）。个人觉得这个可以先不实现？
> 
> 这个想的时候只是个optional功能，当初构思的实现跟g桑思路差不多，我也觉得可以暂时搁置

嗯嗯，这个先暂时搁置

> 
> > > * 不同服用户量
> > 
> > 
> > 用户的话，是多服共用账号的，一个账号可以上传多个服务器的数据
> 
> 那可以考虑不同服上传量对比？比如小马活动各个服上传量分别是多少（考虑单独开一个页面？）

好诶，感觉这个得放到“stage 2”去实现，毕竟跨服务器的话，ui上还需要做一些考量避免混淆~

> 
> ps:额外添加
> 
> * 捐赠用户量捐赠名单（放到致谢页面？）

现在已经整理出了一份捐赠名单，是石墨表格；v3上线的时候会把链接放上~

**Comment by GalvinGao** [comment]
> @GalvinGao 
> 
> > > * 目前正在使用用户数
> 
> > 
> 
> > “正在使用的用户数” 具体是如何计算呢？主要是，“现在在线”这部分我们现在使用的是Google Analytics，GA那边并不支持外部api调用；而自己实现一个相关功能，通常会带来一些不必要的服务器负载（如，我们需要记录每个ip对网页的访问，若此ip在两小时内无再次刷新则判断已经离线）。个人觉得这个可以先不实现？
> 
> 
> 
> GA has APIs.
> 
> [DevGuides](https://developers.google.com/analytics/devguides/reporting/core/v4)
> 
> [Metrics](https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/)
> 
> [Query explorer](https://ga-dev-tools.appspot.com/query-explorer/)
> 
> 
> 
> In the metrics, there is `ga:sessions`, `ga:1dayUsers`, `ga:14daysUsers`, `ga:14daysUsers`.
> 
> If possible, GA can set user id which can analyze user behaviors better in `v3.0.0`.
> 
A lot of people is blocking GA do it might not be a reliable source.
> 
> For Cloudflare which the `penguin-statistics.io` uses, there is an [API](https://api.cloudflare.com/#zone-analytics-dashboard) which can load unique ips (and other CDN information) over a period of time which can be used to track online users.

This is a doable approach. We might need to dig deeper about the accuracy of the APU.

> However, I do not know whether there is an API for the CDN server of `penguin-statistics.cn`
We are using Aliyun for the CDN of `.cn` site; they do provide such api at https://www.alibabacloud.com/help/zh/doc-detail/91109.htm . Need more investigation.

**Comment by GalvinGao** [comment]
已在 `v3.1.0` 中实现。Closing
