### ISSUE TITLE
Planner chapter err in overseas server

### ISSUE THREAD

**Issue by Kouheng** [penguin-statistics/frontend-v2#315]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36`

### URL
`https://penguin-stats.io/planner`

### Steps to reproduce
切换服务器到日 美服时，可以见到排除关卡中的6章及6章以后的选项是消失的，但规划中还是会出现6 7章的刷图

### What is expected?
6 7章的选项依然出现，但呈现灰色(不可选)
或是选项不可见，也不会被规划进刷图

### What is actually happening?
选项消失但规划还在

---
如果解决了这个BUG，可以考虑一并在排除的章节底下加上disable整个章节的功能，就像过去版本中的"不考虑第6章"按钮，对于练度不足或是海外服务器的小伙伴们还是比较友善的

**Comment by GalvinGao** [comment]
Planner 后端将在近两个星期内完成新 API 的适配工作；在此之前我们也将优化关卡选择器过滤逻辑，并尽快上线修复。
感谢反馈！
