### ISSUE TITLE
掉落汇报改进

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#32]
### What problem does this feature solve?
掉落汇报的所有item排列，在iphoneX下（宽度375）所有item是一行一个，竖直排列的，用户滚屏操作偏多。可否调整大小，以及padding，让这个宽度下能显示两列，或者更多？

### What does the proposed API look like?
我还是认为目前的 "素材   0 -"占地太大了，也可以考虑素材图右下重叠一个小圆显示数目，下方放加减号？
还可以继续提升：减号使用频率远低于加号，考虑改进。

**Comment by GalvinGao** [comment]
The design will be something like this:
![IMG_E5703FD66BE4-1](https://user-images.githubusercontent.com/12567059/63215934-45962600-c160-11e9-921e-5f3748fff2df.jpeg)
