### ISSUE TITLE
Furniture drop report problem

### ISSUE THREAD

**Issue by Ericli0708** [penguin-statistics/frontend-v2#322]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0`

### URL
`https://penguin-stats.io/report/main_6/main_06-14`

### Steps to reproduce
This problem occurred at all drop report pages. Submit one drop report with "Furniture Drop: No" turn on.

### What is expected?
1. Furniture drop switch should turn off after every submit.
2. The text of this switch should show "Furniture Drop: Yes" when this swtich turn on, show "Furniture Drop: No" when this switch turn off. 
3. This should apply to all languages. 

### What is actually happening?
After submitting one furniture drop report, the switch remain "on" which need to mannually switch off. (Causing wrong furniture drop report when you forget that.) Also, the text of this switch don't show current state. It keep "Furniture Drop: No" all the time.

**Comment by Ericli0708** [comment]
![图片](https://user-images.githubusercontent.com/33204722/82275597-bd2a0780-99b5-11ea-89d1-a6edab3fb760.png)
![图片](https://user-images.githubusercontent.com/33204722/82275619-cca95080-99b5-11ea-9e04-0eb1bec041d0.png)

**Comment by AlvISsReimu** [comment]
Thanks for reporting this issue. We will fix it in the next release.

**Comment by AlvISsReimu** [comment]
resolved
