### ISSUE TITLE
AP,CE,LS类似的关卡报告没加入数据里

### ISSUE THREAD

**Issue by Aquastic** [penguin-statistics/frontend-v2#325]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36`

### URL
`https://penguin-stats.io/report`

### Steps to reproduce
当你只是输入没有掉落和没按其他东西（因为除了furniture，其他的都没有的按）。它会显示"No items selected.Are you sure you want to submit this record?"，然后是"Confirm submitting this record?"

### What is expected?
两个按了confirm 后应该是把那场没掉落furniture的资料放进去资料库里。

### What is actually happening?
两个按了Confirm 后，虽然显示"Successfully Submitted"，但是检查了后，没有把没有掉落的数据加入里面。

---
加油0 7 0)/

**Comment by AlvISsReimu** [comment]
感谢反馈与支持！这个确实是我在写查询时的一个漏洞…将于下个版本release中修复

**Comment by AlvISsReimu** [comment]
resolved
