### ISSUE TITLE
第六章和第七章的关卡出现在其他的服务器里

### ISSUE THREAD

**Issue by Aquastic** [penguin-statistics/frontend-v2#334]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36`

### URL
`https://penguin-stats.io/planner`

### Steps to reproduce
在国服那里没×掉第六章和第七章，然后转去其他服的

### What is expected?
即使第六章和第七章没×，其他服应该不会推荐第六章和第七章的关卡的

### What is actually happening?
转到其他服，他们还是推荐第六章和第七章，即使其他服的”移除关卡“里没有第六章和第七章

---
安安，我又回来了XD。加油~~~

**Comment by GalvinGao** [comment]
xD 在我们更新ArkPlanner后，此bug将会被修复~
