### ISSUE TITLE
没显示照片

### ISSUE THREAD

**Issue by Aquastic** [penguin-statistics/frontend-v2#335]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36`

### URL
`https://penguin-stats.io/planner`

### Steps to reproduce
就你要刷的素材从ark-nights的网站放到这里（或者只是手动放你要的素材调好）

### What is expected?
在SYNTESES和VALUE的图片正常显出

### What is actually happening?
没显示到图片

---
https://cdn.discordapp.com/attachments/431244563357761546/717639461315280906/unknown.png
以上的是图片，加油0 7 0)/

**Comment by GalvinGao** [comment]
你好，这是由于上游planner最近更新到了使用itemid进行通讯的新协议；我们将在近几天更新主站适配~

**Comment by Aquastic** [comment]
啊，了解了0 7 0)b

**Comment by GalvinGao** [comment]
诶嘿 这个应该早就修复了；最近几天我们就会 release 新版的 Planner，根除这个问题w
