### ISSUE TITLE
手机端标题栏上，页面标题overflow

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#34]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36`

### URL
`https://penguin-stats.io/`

### Steps to reproduce
在375宽度（iPhone X）下，标题过长会触发ellipsis，影响观感。用户名比较长的情况下甚至一个字都显示不下。
![image](https://user-images.githubusercontent.com/25188552/62989200-f4063800-bdfb-11e9-927a-8bbc20044a6f.png)

### What is expected?
考虑根据标题内容调整字号？

### What is actually happening?
N/A

**Comment by cyj5230** [comment]
感觉手机版的语言选项和夜间模式可以放到汉堡键中

**Comment by GalvinGao** [comment]
> 感觉手机版的语言选项和夜间模式可以放到汉堡键中

将采用此方法 🥇

> 标题过长会触发ellipsis

移动选项后，考虑到移动端toolbar会是dense样式，可以缩小用户名标签的padding和/或margin
