### ISSUE TITLE
Rounding causes inaccurate battle counts in ArkPlanner

### ISSUE THREAD

**Issue by Idran** [penguin-statistics/frontend-v2#341]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36`

### URL
`https://penguin-stats.io/planner`

### Steps to reproduce
Set up a scenario in ArkPlanner where the total number of resources needed is less than half of the expected number of drops from the optimum stage; a good way to do this is setting up one needed Orirock, as the optimum stage (S2-5) drops an estimated 3.5 per run.

### What is expected?
The planner will display one battle needed in the stage to complete the plan.

### What is actually happening?
The planner will display zero battles needed in the stage to complete the plan

https://i.imgur.com/qgPfK8W.png

---
I'm pretty sure this is happening because the planner is inappropriately rounding when it should be taking the ceiling. In the above specific case, for example, I'm fairly sure it's calculating the expected number of runs as 1/3.5 ~= 0.28, and either rounding that down to 0 or taking the floor of the value. 

Any decimal number of expected runs would always require one run in practice, even outside the less-than-one case: like, for example, if the expected value for number of runs of a stage is, say, 2.2, in practice since you can't run a stage partially, that means on average you'd need to run that stage three times and end up with a slight overage.

Because of this, ArkPlanner should be displaying the ceiling of the estimated number of runs, not the round or the floor.

**Comment by GalvinGao** [comment]
Thanks for reporting this issue. We are currently working on a refactor on Planner and this shall be fixed in the next release.
