### ISSUE TITLE
Average Stage Clear Time

### ISSUE THREAD

**Issue by tainn** [penguin-statistics/frontend-v2#342]
### What problem does this feature solve?
When the sanity consumption and drop rate for a single material is almost the same if not the exact same on two different stages, then the average stage clear time can be the deciding factor of which to choose. It could stand as the final priority factor for players to ultimately decide on one stage.

### What does the proposed API look like?
An additional column that displays the average stage clear time (at 2x speed, default auto deploy).

The primary issue I see would be the gathering of samples. Contrary to the relatively simple sampling of drops, this part would require accurate timing, meaning that an external timer would be required to run the tests or samples.

**Comment by GalvinGao** [comment]
We think by utilizing the Minimal Clear Time, calculated as "the total duration needed until the last enemy has appeared", as displayed on [PRTS Wiki (Chinese)](http://ak.mooncell.wiki/).
E.g. [Stage 0-1](http://ak.mooncell.wiki/w/0-1_%E5%9D%8D%E5%A1%8C) the clear time has shown as `1分3.7秒` which means `1m3.7s`.
We'll be implementing this soon ;)
