### ISSUE TITLE
Can't select Rhodes Island Supplies on the Report Drops

### ISSUE THREAD

**Issue by umisan09** [penguin-statistics/frontend-v2#343]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36`

### URL
`https://penguin-stats.io/report/main_1/main_01-07`

### Steps to reproduce
1.Go Report Drops(e.g.https://penguin-stats.io/report/main_1/main_01-07)
2.Select Drops(i think noname item is Rhodes Island Spplies)
3.If noname item select I can't submit drop report

No Select noname item -> i can submit  drop report

### What is expected?
Select Rhodes Island Supplies and send drop report

### What is actually happening?
I can't report Rhodes Island Spplies

**Comment by AlvISsReimu** [comment]
I made a mistake when I imported drop info for new items. It should have been fixed now:)
