### ISSUE TITLE
Add stage existence

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#346]
### What problem does this feature solve?
Now in the stage selector of 'by stage', some non-exist stages will show up.

### What does the proposed API look like?
Add existence attribute to stage, and do existence check wherever stage is used. Note that this issue has relationship with stage existence: https://github.com/penguin-statistics/frontend-v2/issues/323

**Comment by AlvISsReimu** [comment]
补充：
1. report和planner的stage selector
zone和stage都要做到exist为true，且符合open和close的time。对于stage，额外要求dropInfo不为空。
2. by stage的stage selector
zone和stage都要做到exist为true，但是需要无视时间，因为查看结果要看到所有的。对于stage，无视dropInfo。

**Comment by GalvinGao** [comment]
Implemented in 415f9bc3ab07810e6b572a6b7c053a840350e62d
