### ISSUE TITLE
Add item and stage filters to matrix API

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#348]
### What problem does this feature solve?
Sometimes user may want filtered drop results.

### What does the proposed API look like?
Add two parameters:
- itemFilter
- stageFilter

Both of them are comma separated list of itemId/stageId.

**Comment by GalvinGao** [comment]
Issue moved to [penguin-statistics/backend #46](https://github.com/penguin-statistics/backend/issues/46) via [**ZenHub**](https://www.zenhub.com/)
