### ISSUE TITLE
AWS outbound data usage is too high

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#349]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36`

### URL
`https://penguin-stats.io/`

### Steps to reproduce
N/A

### What is expected?
- Improve random image algorithm.
- Lower the quality to 1/4.

### What is actually happening?
Each background image has ~30hit per hour. For a 2K background image (webp), there will be ~360MB outbound every day.

**Comment by GalvinGao** [comment]
Replaced with lower quality `webp` and `png` images on AWS S3 and has enabled access log. Will be monitoring the visitor behavior in the upcoming days.
Not closing this issue due to further investigation needed, but will downgrade priority and add corresponding label(s).

**Comment by AlvISsReimu** [comment]
We still need to make change on the background random algorithm we discussed last weekend.
