### ISSUE TITLE
手机端团队成员页面组件拥挤

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#35]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36`

### URL
`http://localhost:8083/about/members`

### Steps to reproduce
iphoneX宽度下（375）由于站长联系方式过多导致名字和负责项目被挤压…
![image](https://user-images.githubusercontent.com/25188552/62989030-53b01380-bdfb-11e9-9f98-0bc4e349e089.png)

### What is expected?
可以考虑把联系方式换一行？

### What is actually happening?
N/A

**Comment by AsahiLuna** [comment]
可以考虑使用[expansion-panels](https://vuetifyjs.com/zh-Hans/components/expansion-panels)？可以将额外信息放入拓展面板内
