### ISSUE TITLE
Report page layout adjustment

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#368]
### What problem does this feature solve?
Users need to scroll to finish the report process, which is inconvenient.

### What does the proposed API look like?
Make report page into two columns.
On the left: Zone name and Stage code, report regulations and tips, some other buttons, and some other stuff in the future can be put here, like the last report time and details.
One the right: Regular, special and extra drops, furniture, submit and clear buttons. Note that we may need to put regular and special drops into the same line. (What if they cannot be put into one line? Discussion needed.) Also, reduce the indent between every two lines.

**Comment by GalvinGao** [comment]
Already modified page layout in v3.3.2; still need to make Special & Extra drop into one line (`display: flex-inline`?)

**Comment by AlvISsReimu** [comment]
is this done in v3.4.0? @GalvinGao

**Comment by GalvinGao** [comment]
> is this done in v3.4.0? @GalvinGao 

Nope. Though I do think to keep them in separated lines provides maximum recognizability and maximum extent to avoid misinterpretation of drop types.
Consider just to keep it as-is?

**Comment by GalvinGao** [comment]
Implemented.
