### ISSUE TITLE
Favorite Stages

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#370]
### What problem does this feature solve?
There might be several stages that user report or see drop rates frequently. It is inconvenient for users to find corresponding zones and stages every time.

### What does the proposed API look like?
Users are able to mark one stage as favorite. Then it'll show at the top of the stage selector. (Should take one entire line, if more than one line then make it expandable. Only report and by stage page need this. Planner does not.)
On report page, next to the stage code we can set up a 'star' icon for users to mark as favorite.
On 'by stage' page, it is okay to put it below the drop rate table, but I still think we should put a 'star' icon next to the stage code as well. This design is consistent to the report page.

**Comment by GalvinGao** [comment]
Implemented in v3.4.0. Closing
