### ISSUE TITLE
'By stage' page layout adjustment

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#371]
I'd like to summarize the new features and changes we are gonna implement on the 'by stage' page.
First of all, we can provide an expandable panel on top of the drop rate table. It may contain:
- Sample size filter (#181)
- Drop rate filter
- ~~Stage availability filter (#323)~~
- ...

If more than one filter is applied (which means that not all records are shown), we can show something to remind the user.

Second, under the drop rate table, we can show some other statistical data for this stage, such as:
- Drop Pattern Results (#208)(https://github.com/penguin-statistics/backend/pull/43)
- Mark as Favorite Stage (#370)
- Maybe more graphs?
- More stage statistical data? For example, sample num in 24 hrs
- Export CSV (#261 )
- ~~Stage Info, such as AP cost and min clear time (#342)~~

Third, there are some other UI changes.
- ~~Switch to adjacent stages using small arrows (#344)~~
- any others?

**Comment by GalvinGao** [comment]
New release candidate 3.3.7 has implemented large portion of this issue except the following items:
- Export CSV
- More stage statistics

**Comment by AlvISsReimu** [comment]
> New release candidate v3.3.7 has implemented a large portion of this issue except the following items:
> 
> * Export CSV
> * More stage statistics

For 'Export CSV', I think we may not need this...? Since the graph library you are using has this feature.
For 'More stage statistics', now it is under 'Site Stats', so it's good now.

I think this issue can be marked as done after the release.
