### ISSUE TITLE
日服掉落汇报无法汇报主线剧情关卡的掉落

### ISSUE THREAD

**Issue by Matrix-J-H** [penguin-statistics/frontend-v2#388]
### What problem does this feature solve?
可以让日服玩家汇报日服主线剧情素材的掉率

### What does the proposed API look like?
跟国服的掉率汇报一样的使用方法即可

**Comment by GalvinGao** [comment]
日服主线数据由于正在进行临时内部维护，因此可能会暂时不可用；预计将于若干小时后恢复，敬请谅解QvQ

**Comment by Matrix-J-H** [comment]
了解
