### ISSUE TITLE
日服刷图规划器刷图策略错误

### ISSUE THREAD

**Issue by Matrix-J-H** [penguin-statistics/frontend-v2#389]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36`

### URL
`https://penguin-stats.io/planner`

### Steps to reproduce
输入你的资源以及你想要的资源数量，点击计算规划

### What is expected?
主线剧情的刷图和资源掉落策略

### What is actually happening?
就算删除掉了岁过灯华的资源掉落选项。规划器仍然提示只通过岁过灯华获得目标资源。

---
切换到韩服使用规划器也有一样的问题，美服看起来是正常的。

**Comment by GalvinGao** [comment]
您好，我们这边尝试复现了此问题，但是都正常；如果可以还请您分享一下配置文件，位置在【导入/导出】里~

**Comment by GalvinGao** [comment]
This issue has been closed due to inactivity. Feel free to reopen it if the issue persists.
