### ISSUE TITLE
服务器切换至韩服后无法再次切换

### ISSUE THREAD

**Issue by sjfhsjfh** [penguin-statistics/frontend-v2#402]
#### Environment

Firefox Daylight 29.1 (3022) on iOS 14

#### Problem

服务器切换到韩服后无法再次切换到其他服务器，刷新网页无效且网络状况良好

#### URL

https://penguin-stats.io

望尽快解决🙏

**Comment by GalvinGao** [comment]
您好：
首先感谢您提交此 Issues ;)
在尝试于运行 iOS 14.0 (18A373) 的 iPhone Xs Max 上启动的 Firefox Daylight 29.1 (3022) 内进行复现时并未发现问题。
其中，复现过程中所采取的步骤为：
1. 打开 https://penguin-stats.io
2. 等待页面完全加载完毕（顶部进度条消失）后
3. 通过右上角的服务器切换器由默认的“国服”切换至“韩服”
4. 等待页面完全加载完毕（右下角加载指示器消失）后
5. 通过右上角的服务器切换器由默认的“韩服”切换至“国服”
5.1. （此步成功完成）

---

由于复现并未成功，还请您尽可能地提供更多信息。若可以，录屏将是较为高效且推荐的复现方式 ;)

再次感谢您的 Issues ;)

**Comment by GalvinGao** [comment]
Tips: 若您身处于中国大陆网络环境中，还请尝试访问我们的大陆镜像站点；其位于 https://penguin-stats.cn

**Comment by sjfhsjfh** [comment]
问：如何提供录屏（

**Comment by GalvinGao** [comment]
> 问：如何提供录屏（

您可以直接传到这里w 回复框右上角有个 ↑ (Attach Files)，用那个就可以发文件惹！

**Comment by sjfhsjfh** [comment]
移动端（哭

**Comment by sjfhsjfh** [comment]
?

**Comment by sjfhsjfh** [comment]
![Uploading D1E11549A8A503FAE25884D305C5BF75.png…]()

**Comment by sjfhsjfh** [comment]
![ScreenCap](https://user-images.githubusercontent.com/58244206/98797360-6888b600-2447-11eb-9b42-2bd031440aac.gif)

好力！
虽然已经多次尝试在其他设备上复现未成功（逃）

**Comment by GalvinGao** [comment]
ah已经收到你的邮件了（实在抱歉忘记回了（？
我这边尝试去复现了也怎么都没成功qvq
要不试一下在设置界面重置所有数据看看是否能解决问题？:D

**Comment by sjfhsjfh** [comment]
已解决！非常感谢！
又可以快乐刷1-7了（逃

**Comment by GalvinGao** [comment]
> 已解决！非常感谢！
> 又可以快乐刷1-7了（逃

好耶！解决问题了就好！
我们也会持续监控客户端错误反馈来保证不会发生大规模的服务不可用事件 :D

问题已解决；关闭此 Issue~

**Comment by bbaa-bbaa** [comment]
safari14(iOS)以下 的 localstorage 限制仅为5M
如果localstorage满了就无法切换服务器
可能的解决方案
1. ~~杀了localStorage~~
2. ~~在localStorage满了弹框提示用户进行清理~~
![16200101278243500](https://user-images.githubusercontent.com/18095317/116837484-3ccbd900-abfd-11eb-84a9-b22c7b87533a.PNG)
