### ISSUE TITLE
刷图规划遇到奇怪的bug

### ISSUE THREAD

**Issue by po12017po** [penguin-statistics/frontend-v2#403]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36`

### URL
`https://penguin-stats.io/planner`

### Steps to reproduce
我导入
[{"name":"双极纳米片","need":10,"have":2},{"name":"聚合剂","need":10,"have":""},{"name":"白马醇","need":9,"have":5},{"name":"扭转醇","need":0,"have":83},{"name":"三水锰矿","need":11,"have":""},{"name":"轻锰矿","need":0,"have":98},{"name":"五水研磨石","need":3,"have":1},{"name":"研磨石","need":0,"have":35},{"name":"RMA70-24","need":0,"have":4},{"name":"RMA70-12","need":0,"have":12},{"name":"提纯源岩","need":4,"have":""},{"name":"固源岩组","need":8,"have":60},{"name":"固源岩","need":0,"have":55},{"name":"改量装置","need":3,"have":""},{"name":"全新装置","need":0,"have":11},{"name":"聚酸酯块","need":4,"have":""},{"name":"聚酸酯组","need":0,"have":20},{"name":"聚酸酯","need":0,"have":137},{"name":"酯原料","need":0,"have":58},{"name":"糖组","need":0,"have":10},{"name":"异铁块","need":6,"have":""},{"name":"异铁组","need":0,"have":6},{"name":"酮凝集组","need":5,"have":16},{"name":"聚合凝胶","need":0,"have":5},{"name":"凝胶","need":0,"have":15},{"name":"炽合金块","need":6,"have":""},{"name":"炽合金","need":0,"have":3},{"name":"晶体元件","need":0,"have":12}]
这串数据然后规划结果，我要六个炽合金块，我只有三个炽合金，他却只叫我刷两次s3-6，获得不到一块的炽合金，这显然有问题
https://i.imgur.com/C0c7fk7.jpg
https://i.imgur.com/ng0MR9l.jpg

### What is expected?
再刷三个炽合金

### What is actually happening?
只有规划0.9块炽合金

**Comment by GalvinGao** [comment]
您好~ 感谢汇报此 Issues
经判断，此行为为预期行为：Planner 同时会考虑合成成本，并在合成成本低于刷图成本时提供推荐的合成数量而非推荐多刷一次对应关卡。您可通过 “合成列表” 查看推荐的合成物品及对应的合成次数。
![image](https://user-images.githubusercontent.com/12567059/99351987-c7817b80-28dc-11eb-8687-c211e541d89b.png)
在合成后，对应物品的需求就应该满足了 :D

**Comment by po12017po** [comment]
> 您好~ 感谢汇报此 Issues
> 经判断，此行为为预期行为：Planner 同时会考虑合成成本，并在合成成本低于刷图成本时提供推荐的合成数量而非推荐多刷一次对应关卡。您可通过 “合成列表” 查看推荐的合成物品及对应的合成次数。
> ![image](https://user-images.githubusercontent.com/12567059/99351987-c7817b80-28dc-11eb-8687-c211e541d89b.png)
> 在合成后，对应物品的需求就应该满足了 :D
我在看了下发现是勾大量需求经验变成这样的，没勾另外两个，取消勾大量需求经验就变正常了

**Comment by SQRPI** [comment]
因为勾大量需求经验之后, 铁会推荐刷S4-1, 其中有少量炽合金掉落, 因为掉落较少, 没有在关卡列表中显示
不勾大量需求经验时, 铁的推荐关卡是7-18, 没有炽合金掉落

**Comment by po12017po** [comment]
> 因为勾大量需求经验之后, 铁会推荐刷S4-1, 其中有少量炽合金掉落, 因为掉落较少, 没有在关卡列表中显示
> 不勾大量需求经验时, 铁的推荐关卡是7-18, 没有炽合金掉落

理解了，感谢回答

**Comment by GalvinGao** [comment]
问题已解决，将关闭issues；若有其他问题欢迎reopen！;)
