### ISSUE TITLE
新版Edge点击右键时不能减少物品数量

### ISSUE THREAD

**Issue by hywo-x** [penguin-statistics/frontend-v2#406]
（已解决）
如题，Chromium版Edge，在掉落汇报里面点击右键的时候，会弹出菜单而非减少物品数量（虽然也可以直接清空重来）
Edge版本：版本 87.0.664.60 (官方内部版本) (64 位)
![点击右键会弹出菜单](https://user-images.githubusercontent.com/44500698/102159672-f29cc200-3ebe-11eb-8483-da06cbd28d9f.png)

**Comment by GalvinGao** [comment]
您好！
呜，我没有成功复现这个问题；使用 Chromium 内核的 Edge，版本 87.0.664.60 (官方内部版本) (64 位)，修订 23fbc5c433ca16cabc81bf118f0e6fd9f7368f1e
请您尝试一个一个地移除浏览器扩展查看问题是否依旧存在？

<details>
<summary>（附：我这里已安装的浏览器扩展列表）</summary>

- 1 Password X
- Dark Reader
- Microsoft Editor
- Proxy SwitchyOmega
- Quick QR Code Generator
- Tampermonkey
- uBlock Origin
- FireShot
- EditThisCookie
- Google Translator
- Octotree
- Picture-in-Picture Extension (by Google)
- Refined GitHub
- Sourcegraph
- Vue.js devtools
- WhatFont
- WhatRuns
- ZenHub for GitHub

</details>

**Comment by bbaa-bbaa** [comment]
猜测是网页限制解除之类的脚本所致

**Comment by hywo-x** [comment]
解决了，是我新下载的提取网页图片的插件

**Comment by GalvinGao** [comment]
问题已解决。Closed.
