### ISSUE TITLE
刷图规划器合成推荐不准确 Inaccurate planner synthesize suggestions

### ISSUE THREAD

**Issue by Jason-CHK** [penguin-statistics/frontend-v2#407]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

### URL
`https://penguin-stats.io/planner`

### Steps to reproduce
I used the following configuration in the planner:

```
{"@type":"@penguin-statistics/planner/config","items":[{"id":"30135","have":5,"need":5},{"id":"30125","have":7,"need":5},{"id":"30115","have":8,"need":5},{"id":"30074","have":10,"need":10},{"id":"30073","have":26,"need":20},{"id":"30084","have":21,"need":10},{"id":"30083","have":18,"need":20},{"id":"30094","have":10,"need":10},{"id":"30093","have":20,"need":20},{"id":"30104","have":10,"need":10},{"id":"30103","have":17,"need":20},{"id":"30014","have":15,"need":10},{"id":"30013","have":19,"need":20},{"id":"30012","have":44},{"id":"30011","have":32},{"id":"30064","have":8},{"id":"30063","have":12,"need":20},{"id":"30062","have":4},{"id":"30061","have":6},{"id":"30034","have":14},{"id":"30033","have":48,"need":20},{"id":"30032","have":54},{"id":"30031","have":38},{"id":"30024","have":21,"need":10},{"id":"30023","have":21,"need":20},{"id":"30022","have":127},{"id":"30021","have":16},{"id":"30044","have":25,"need":10},{"id":"30043","have":30,"need":20},{"id":"30042","have":60},{"id":"30041","have":21},{"id":"30054","have":10,"need":10},{"id":"30053","have":5,"need":20},{"id":"30052","have":12},{"id":"30051","have":17},{"id":"31014","have":25,"need":10},{"id":"31013","have":28,"need":20},{"id":"31024","have":10,"need":10},{"id":"31023","have":24,"need":20},{"id":"30145","have":5,"need":5},{"id":"31034","have":10,"need":10},{"id":"31033","have":3,"need":20}],"options":{"byProduct":true,"requireExp":true,"requireLmb":true},"excludes":[]}
```

After calculating the planner gives the following synthesize suggestions:

* `Device` * 3
* `Integrated Device` * 3
* `Polyketon` * 8
* `Aketon` * 10
* __`Polymerized Gel` * 4__

The `Polymerized Gel` suggestion is incorrect, since I need only 10 and already have 25. I also have 5/5 `晶体电子单元` which is the only higher level item that can be synthesized using `Polymerized Gel`.

Even if I increase the number of `Polymerized Gel`s I have from 25 to 29 without changing other numbers, the planner still suggests me to synthesize 4 more `Polymerized Gel`s.

### What is expected?
The planner should not suggest me to synthesize any more Polymerized Gels.

### What is actually happening?
The planner always suggests me to synthesize 4 more Polymerized Gels, even if I increase the number of Polymerized Gels I have.

---
I ran into this bug when synthesizing items using the planner. It keeps suggesting me to synthesize Polymerized Gels and I got confused.

I initially filed the bug under [backend](https://github.com/penguin-statistics/backend/issues/60) by mistake. I have closed that issue.

**Comment by Jason-CHK** [comment]
Took a look at frontend and backend code. Seems like the planner feature is supported via a POST request to the backend, instead of directly calculated in frontend: [exit point](https://github.com/penguin-statistics/frontend-v2/blob/dev/src/apis/planner.js#L5)

However in the backend [repo](https://github.com/penguin-statistics/backend) I couldn't find any class supporting `/plan` endpoint. Am I looking at the wrong place?

**Comment by AlvISsReimu** [comment]
Thanks for reaching out.

Actually ArkPlanner is running on another service, and this is [ArkPlanner's repo](https://github.com/ycremar/ArkPlanner), currently maintained by @SQRPI.

@SQRPI Could you please take a look into this issue? Thanks!

**Comment by SQRPI** [comment]
This is because you have turned on the synthesis by-product option, so we would suggest that you synthesize all the materials you have to get by-products.

在 2020-12-15 16:56:31，AlvISs_Reimu <notifications@github.com> 写道：


Thanks for reaching out.

Actually ArkPlanner is running on another service, and this is ArkPlanner's repo, currently maintained by @SQRPI.

@SQRPI Could you please take a look into this issue? Thanks!

**Comment by SQRPI** [comment]
This is because you have turned on the synthesis by-product option, so we would suggest that you synthesize all the materials you have to get by-products.

**Comment by Jason-CHK** [comment]
Makes sense, thanks for the explanation!

Closing as WAI.
