### ISSUE TITLE
API: Formula: Typo in formula 31034, cost item 1: 30133 instead of 31033

### ISSUE THREAD

**Issue by jake-o** [penguin-statistics/frontend-v2#413]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36`

### URL
`https://penguin-stats.io/PenguinStats/api/v2/formula`

### Steps to reproduce
1. Download JSON file at URL.
2. Search for recipe for item 31034 -> first cost item id is 30133.
3. Try https://penguin-stats.io/PenguinStats/api/v2/items/30133 -> 404 not found

### What is expected?
All cost items exist.

### What is actually happening?
Item can not be found.

---
Probably a typo. I think the correct id should be 31033.

**Comment by jake-o** [comment]
Additionally, there is a formula for an item 31035 that can not be found:
https://penguin-stats.io/PenguinStats/api/v2/items/31035

**Comment by GalvinGao** [comment]
@AlvISsReimu ping on this?

**Comment by FlandiaYingman** [comment]
Fixed in https://github.com/penguin-statistics/backend-next/issues/50

**Comment by GalvinGao** [comment]
Can confirm this is fixed in https://github.com/penguin-statistics/backend-next/issues/50. Closing.
