### ISSUE TITLE
Cannot load main page via Edge browser on Android 

### ISSUE THREAD

**Issue by fyc1007261** [penguin-statistics/frontend-v2#426]
![Screenshot_20210124-145851](https://user-images.githubusercontent.com/26542633/105623448-b90f8d00-5e54-11eb-8fea-8898b575bc2e.jpg)
### Environment
`Mozilla/5.0 (Linux; Android 11; IN2010) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/45.09.4.5079`

### URL
`https://penguin-stats.io/`

### Steps to reproduce
Use Edge browser on Android to access the main page. It says that I'm using an outdated browser which cannot load the page.

### What is expected?
The main page shows. 

### What is actually happening?
The page says it failed to load the page as my browser is outdated.

**Comment by fyc1007261** [comment]
Seems that the problem has been solved

**Comment by GalvinGao** [comment]
> Seems that the problem has been solved

Sorry for forgetting to close this issue 😅.

Fixed in hot-fix of v3.4.2 where we refactored the app bootstrap logics.
