### ISSUE TITLE
Wrong event name in Japanese

### ISSUE THREAD

**Issue by umisan09** [penguin-statistics/frontend-v2#434]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36`

### URL
`https://penguin-stats.io/result/stage`

#### English
change language to japanese
wrong event name(RI-1~RI-9)

#### Japanese
言語を日本語のときに間違ったイベント名が出る

#### English
Is displayed as 帰還！密林の長(The Great Chief Retuns)
帰還！密林の長 is Event name in japanese
#### Japanese
帰還！密林の長とイベント名が表記される

#### English
Is displayed as ハートオブスチール(HEART OF STEAL)
HEART OF STEAL is HEADHUNTING name

#### Japanese
ハートオブスチールとイベント名が表記されている
ハートオブスチール(HEART OS STEAL)はイベントスカウトの名前である

**Comment by AlvISsReimu** [comment]
修正しました。
ご報告ありがとうございます。
