### ISSUE TITLE
用户上传素材掉落后，将素材数量加入到刷图规划中

### ISSUE THREAD

**Issue by pj520** [penguin-statistics/frontend-v2#452]
### What problem does this feature solve?
用户按照刷图规划器的建议刷图之后，如果忘记自己刷图次数，再次进行刷图规划时，可以不用再自己手动改变素材数量。减轻用户重复从库存中查找特定素材的操作。

### What does the proposed API look like?
无

**Comment by GalvinGao** [comment]
感谢提出建议；

#423 讨论了相同的内容，将关闭此议题。请关注 #423 之后进行的讨论、您亦可加入 #423 进行讨论
