### ISSUE TITLE
前端TechX广告Backdrop覆盖问题

### ISSUE THREAD

**Issue by JokeNeverSoke** [penguin-statistics/frontend-v2#457]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36`

### URL
`https://penguin-stats.io/`

### Steps to reproduce
点击“本内容由赞助商提供”中的问号后显示的modal被backdrop覆盖了

### What is expected?
未被覆盖

### What is actually happening?
被黑色backdrop覆盖，影响阅读

**Comment by JokeNeverSoke** [comment]
页面截图如下：
![ScreenShot Tuesday 11-43 首页 │ 企鹅物流数据统计-Google Chrome](https://user-images.githubusercontent.com/45055133/122859834-3a5d4400-d34f-11eb-9322-4d7969523873.png)

**Comment by GalvinGao** [comment]
您好！此行为为预期行为；可能由于叠层未设置为正确的半透明亮度修改颜色而导致modal难以辨识；我们将于近期更换广告内容后对此问题进行修复。

感谢您的反馈！
Closing due to expected behavior and an available fix is available in the release candidate version.
