### ISSUE TITLE
请求添加另外两个别传关卡的入口

### ISSUE THREAD

**Issue by y19940406** [penguin-statistics/frontend-v2#467]
### What problem does this feature solve?
在国服密林悍将归来活动入别传后，我想查看喧闹法则和密林悍将归来两个活动入别传之后材料的掉率，以及是否值得非活动时间或者个别时候只缺单材料的时候刷，但由于找不到入口没办法查看和上报数据，并且计算工具也不会考虑到这两个别传

### What does the proposed API look like?
希望能够在别传区添加这两个活动的入口，可以像其他关卡一样上传和统计掉落数据

**Comment by GalvinGao** [comment]
此前已添加，忘记关闭了~ Closed
