### ISSUE TITLE
iPad客户端有按钮不响应点击

### ISSUE THREAD

**Issue by zbodo** [penguin-statistics/frontend-v2#498]
### Environment
`Mozilla/5.0 (iPad; CPU OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Mobile/15E148 Safari/604.1`

### URL
`https://penguin-stats.io/`

### Steps to reproduce
iPad客户端的侧边栏里关于本站中的“团队成员”、“更新记录”、“内容来源”项点击无反应

### What is expected?
点击按钮进入对应界面

### What is actually happening?
无响应

**Comment by GalvinGao** [comment]
你好，感谢反馈；新版前端理论上已经修复了这部分的问题；若你使用的是 iOS App，则还需要等待我们发布新版本；若你使用的是 Web App，则可以刷新页面观察问题是否继续存在～

**Comment by GalvinGao** [comment]
你好，请问这个问题您那边还能复现嘛

**Comment by zbodo** [comment]
版本3.6.11的客户端仍然存在这个问题.设备是iPadOS 15.4.1的iPadmini5
@GalvinGao

**Comment by zbodo** [comment]
另外，截图识别、高级查询按钮也有同样的问题

**Comment by GalvinGao** [comment]
这部分问题已于 v3.7.1 修复；对应版本已送审，还需要等待 App Store 审核后才可更新，还请稍候

**Comment by GalvinGao** [comment]
v3.7.1 已过审，还请下载更新后看看问题是否依旧存在？这边使用 iPadOS 15.4 已经无法复现了～

**Comment by zbodo** [comment]
新版没有问题了
