### ISSUE TITLE
Some of the site in Link Exchange are being no more maintained

### ISSUE THREAD

**Issue by FlandiaYingman** [penguin-statistics/frontend-v2#500]
Status of these sites are shown below:

1. 明日方舟工具箱 - not quite sure, last updated on 2021/11/01
2. Ark Tools - no more maintainance
3. 刷素材推荐一图流 - no response
4. Kokodayo Arknights Data - AccessDenied
5. 最佳招聘网站 - not quire sure, last updated on 2021/08/04
6. Konmai Academy - 403 forbidden

Mark them as "no more maintenance"? 
Remove them from Link Exchange? 
Thoughts?

**Comment by GalvinGao** [comment]
Due to the fact they do served helpful content to the community before, personally I would prefer not to simply remove them. Marking those sites with "no longer maintained" would be appropriate and still serve the purpose on providing our user other useful sites surrounding Arknights.
