### ISSUE TITLE
Report Drops: Recognition: Sample did not increase

### ISSUE THREAD

**Issue by jake-o** [penguin-statistics/frontend-v2#510]
Yesterday, I uploaded 15 drops via image recognition, all for stage M8-6.
There was no error and the Loot counts were updated correctly - but not the Sample count:
Server US: https://penguin-stats.io/result/stage/main_8/main_08-09

It is even more apparent if I look at my personal drops:
![M8-6](https://user-images.githubusercontent.com/39053035/165275341-2bf6f421-2f4f-4fbc-aa1f-c790ccf4dd90.png)

I cannot tell you what could have gone wrong - I used the image recognition both for 9-2 and 9-11 without problems, each time on my iPhone (iOS 15.3.1).

Could you please correct the Sample count?

**Comment by GalvinGao** [comment]
Huge apologies for the confusion 😢 . Previously a change has introduced an issue where the multiplier of recognition report haven't been automatically popularized so they stay as `0`. We've identified, fixed the problem and have updated all existing dataset to reflect the fix.

Can you please double-check on your side to see if this already solved the issue? On our side all seems normal now.

**Comment by jake-o** [comment]
Yes, everything seems fixed on my side – thank you very much :+1: 

Admittedly, my Go is not strong enough to pinpoint were exactly the error was – but I will trust you that the fix is somewhere in the PR ;)

(As I do not know your issue policy, I will not close this issue yet. But I consider it solved.)

**Comment by jake-o** [comment]
I have to correct myself.

Yes, the numbers are correct, but the upload failed again.
![R8-6](https://user-images.githubusercontent.com/39053035/165703899-1506f9ee-adf8-4cab-97c8-afb3b77c6f81.jpeg)

**Comment by jake-o** [comment]
My guess:

In https://github.com/penguin-statistics/backend-next/pull/51:

In the third commit, you set Times to 1 in SingleReport:
https://github.com/penguin-statistics/backend-next/pull/51/commits/c8f25026cb1efe3c234f05da6392bcef1bbcc1d9

In the fourth commit, this change is reversed (and Times will probably be initialized with a default value of 0 again?):
https://github.com/penguin-statistics/backend-next/pull/51/commits/4855e89c498f296b3806d93ad8abe1f6f7c9591f

**Comment by jake-o** [comment]
In my personal statistics for R8-6, the sample count is still 0 (should be 16 iirc):
![0653FE23-2FD3-46C2-A922-F23D2359C669](https://user-images.githubusercontent.com/39053035/166021479-951e3106-61e4-4a84-9611-d7a5452f65ad.png)

With „upload failed“, I mean that something went wrong with the upload. The loots are updated, but the sample count did not change - neither in my personal statistics (0 samples) nor in „all“ (6 samples).

**Comment by GalvinGao** [comment]
> In my personal statistics for R8-6, the sample count is still 0 (should be 16 iirc): ![0653FE23-2FD3-46C2-A922-F23D2359C669](https://user-images.githubusercontent.com/39053035/166021479-951e3106-61e4-4a84-9611-d7a5452f65ad.png)
> 
> With „upload failed“, I mean that something went wrong with the upload. The loots are updated, but the sample count did not change - neither in my personal statistics (0 samples) nor in „all“ (6 samples).

My apologies! It seems that I've forgot Alviss is working on a fix regarding this issue. It seems that it have been fixed by a release just rolled out. Could you please double check it again? :D

**Comment by jake-o** [comment]
So:
- The sample count is corrected for my uploads in R8-6
- I uploaded new data (both by stage and by recognition), and the loot and sample count was updated correctly

Everything seems to be working as intended now 👍🏼

**Comment by GalvinGao** [comment]
> So:
> 
> * The sample count is corrected for my uploads in R8-6
> * I uploaded new data (both by stage and by recognition), and the loot and sample count was updated correctly
> 
> Everything seems to be working as intended now 👍🏼

Good to hear! Sorry again for the service interruption. We're planning to roll out a service bulletin to notify users about the recent data inconsistency issues occurred to keep them updated.

I'll then go ahead and close issue. If you'd have any other questions please open another one for the sake of record :D
