### ISSUE TITLE
[Bug]: 汇报被判定为异常

### ISSUE THREAD

**Issue by hanzhou7** [penguin-statistics/frontend-v2#528]
### 环境 // Environment

操作系统 / Operating System: ios
浏览器名称 / Browser Name: 企鹅物流app
浏览器版本 / Browser Version:

### 出现此问题的页面链接 // URL of the page that the problem occurred in

https://penguin-stats.io/

## 您都做了哪些事情/我们如何才能复现这个问题呢？ / What steps did you take to reproduce this problem?
1. sv-4 汇报被判定为异常

## 期望的结果 / What should have happened?
1. 额外物资为赤金和绿经验，但提示只能回报一种
![34E47E30-8ABE-4B60-B40A-A5C54B08AB53](https://user-images.githubusercontent.com/89817481/177130276-6c1c8d97-7e90-4c93-b208-7e3f74342015.png)

## 实际的结果 / What actually happened?
1.
![2B942E8F-23F1-4727-AEE7-AFEC1AE85FD3](https://user-images.githubusercontent.com/89817481/177130309-a74983a5-ac9b-4ca8-85df-e2cb14e53bfe.png)

## 额外的信息 / Any additional information?
1.

**Comment by AlvISsReimu** [comment]
已修复，感谢反馈~
