### ISSUE TITLE
Sorting is very slow on mobile phone when there are too many rows in the table

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#53]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

### URL
`http://localhost:8083/result/item/furni`

### Steps to reproduce
Click on any header to sort results for item "furni" using mobile phone. It takes too much time.

### What is expected?
N/A

### What is actually happening?
N/A

**Comment by GalvinGao** [comment]
Planned to use the Profile feature in DevTools to observe high-cost operations.
