### ISSUE TITLE
[Suggestion]: 异常掉落误判

### ISSUE THREAD

**Issue by heluene** [penguin-statistics/frontend-v2#541]
### 功能或改进建议的相关页面链接 // URL of the page that the suggestion is related to

https://penguin-stats.io/

## 您的功能或改进是针对哪个/哪些功能/模块的？ / What is the feature or improvement related to?
1. 
异常掉落判定
## 如果这是一个改进建议，您感觉这个功能现在存在什么问题？ / If this is an improvement suggestion, what is the problem that this feature currently has?
1.
## 请尽量详述功能或改进建议的改进方案 / How would you describe the improvement you would like to see?
1.

![QQ截图20221013103727](https://user-images.githubusercontent.com/107483017/195486536-0a3d6f74-7bc9-4205-89b5-c1f6c4389fa7.png)
![Screenshot_2022 10 13_10 33 35 747](https://user-images.githubusercontent.com/107483017/195486563-d55f6335-b7a5-42ba-a0ec-4844d674641d.png)
![Screenshot_2022 10 13_10 36 59 630](https://user-images.githubusercontent.com/107483017/195486567-a6a3cd10-7a73-4d60-bd0d-aa4aa4d419d3.png)

**Comment by GalvinGao** [comment]
你好 企鹅物流数据统计不接受一个关卡的**首次通关**汇报哦 因为通常首次通关与此后的非首次通关的掉落物是不一样的 😉

**Comment by GalvinGao** [comment]
但是还是感谢汇报问题哦 事实上非首次通关汇报也会掉落2+经验书 我们于12小时前就已经修复了此问题 但还是感谢报告w
