### ISSUE TITLE
[Bug]: 风雪过境复刻无法截图识别

### ISSUE THREAD

**Issue by TBB000623** [penguin-statistics/frontend-v2#546]
### 环境 // Environment

操作系统 / Operating System: Windows 10 19045.2251
浏览器名称 / Browser Name: Chrome
浏览器版本 / Browser Version: 107.0.5304.123
此外iPadOS app也无法进行同样操作: iPadOS 15.7 Penguin Statistic v3.9.3

### 出现此问题的页面链接 // URL of the page that the problem occurred in

https://penguin-stats.cn/report/recognition

## 您都做了哪些事情/我们如何才能复现这个问题呢？ / What steps did you take to reproduce this problem?
1. 在截图识别处上传识别风雪过境复刻截图BI-7和BI-8若干张
2. 在截图识别处上传识别1-7截图

## 期望的结果 / What should have happened?
1. 正确识别上述截图，并排除龙门币和活动道具识别结果

## 实际的结果 / What actually happened?
1. 1-7上传识别成功
2. BI-7, BI-8截图识别均不成功，并返回“非结算页面截图或内部错误”. 多次上传不同截图发现该问题无论常规掉落材料（非龙门币和活动材料）是否出现均无法识别

![IMG_2390](https://user-images.githubusercontent.com/28950372/205626648-b09d48f1-780e-4ca0-9e58-97eda7ba6dff.PNG)
![test_upload](https://user-images.githubusercontent.com/28950372/205626783-d508a54c-2678-4670-a15f-8347bd5330c2.jpg)

**Comment by GalvinGao** [comment]
您好！感谢反馈此 Issue。

我们已在进行问题调查当中，还正在尝试修复问题，预计今明两天即可修复完成，还请稍候

**Comment by GalvinGao** [comment]
:( 最后我们查到的原因是图标包更新不及时 我们已经开始自动化整套截图识别的新数据更新机制 致力于此后杜绝此情况发生 我们对发生的不便深感抱歉！
