### ISSUE TITLE
[Bug]: 插曲遗尘漫步WD-2识别错误

### ISSUE THREAD

**Issue by Diekk** [penguin-statistics/frontend-v2#548]
### 环境 // Environment

操作系统 / Operating System: win10
浏览器名称 / Browser Name:chrome
浏览器版本 / Browser Version:108.0.5359.99（正式版本）

### 出现此问题的页面链接 // URL of the page that the problem occurred in

https://penguin-stats.io/report/recognition

### 描述 / Description

截图不能识别
![Screenshot_20221214-155633](https://user-images.githubusercontent.com/103347323/207545385-aa4506ee-3192-4f50-9706-ba629d5643c8.png)
![Screenshot_20221214-160438](https://user-images.githubusercontent.com/103347323/207545363-c7120b33-852c-46af-a50d-05f85faca532.png)
![Screenshot_20221214-160147](https://user-images.githubusercontent.com/103347323/207545443-71a2a1e2-b172-48dd-a3a0-66fb9fc33c69.png)
![Screenshot_20221214-155901](https://user-images.githubusercontent.com/103347323/207545618-16ce83d5-4949-4d8f-8670-fad9d0f6d9df.png)
![dfh](https://user-images.githubusercontent.com/103347323/207546414-1601ed88-b46b-42e1-b4a3-7979ab04d447.PNG)
![f](https://user-images.githubusercontent.com/103347323/207546491-4f2cd1b3-0c3c-42e6-8cf4-e1cbd619c831.PNG)

**Comment by GalvinGao** [comment]
你好 我们已更新图标包资源 还请看下有没有修复问题

我们已开始自动化新数据更新流程 以致力于杜绝此类问题再次发生 对带来的不便我们深表歉意qvq

**Comment by Diekk** [comment]
还是不行

***@***.***
发件人: ***@***.***>
发送时间: 2022年12月17日 7:08
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [penguin-statistics/frontend-v2] [Bug]: 插曲遗尘漫步WD-2识别错误 (Issue #548)


你好 我们已更新图标包资源 还请看下有没有修复问题

我们已开始自动化新数据更新流程 以致力于杜绝此类问题再次发生 对带来的不便我们深表歉意qvq

―

**Comment by KumoSiunaus** [comment]
This bug is caused by the resource "stage_index" inputting to the recognition system contains the wrong stageIds of WD-series. The correct stageIds should be "act18d0_02_perm" (for WD-2), which dropInfos are contained, but currently it is "act18d0_02" or "act18d0_02_rep", which contains no dropInfos and cause the bug.

Please fix the incorrectly filtered stage_index. @GalvinGao
