### ISSUE TITLE
[Bug]: 数据库凝胶掉落关卡“玛莉娅・临光   MN-6” 的理智消耗错误

### ISSUE THREAD

**Issue by AbyssAzrael** [penguin-statistics/frontend-v2#549]
### 环境 // Environment

.

### 出现此问题的页面链接 // URL of the page that the problem occurred in

https://penguin-stats.io/result/item/31013

## 您都做了哪些事情/我们如何才能复现这个问题呢？ / What steps did you take to reproduce this problem?
1.
2.
3.

## 期望的结果 / What should have happened?
1.数据库内MN-6的理智消耗为18

## 实际的结果 / What actually happened?
1.数据库内MN-6的理智消耗为15

## 额外的信息 / Any additional information?
1. 数据库与游戏内实际对不上

**Comment by BobLiu0518** [comment]
活动常驻于“别传”后，MN-6的理智由15上调为18，而企鹅物流将活动、活动复刻和别传中的常驻活动分开统计，往下翻即可看到“玛莉娅・临光・别传”的数据，无误。

**Comment by AlvISsReimu** [comment]
> 

感谢回复，我们也再次确认了一下，数据库内活动和复刻的理智消耗都是15，别传是18。
