### ISSUE TITLE
[我不知道这是不是 Bug]: 与 `penguin-stats.cn` 的连接出现问题

### ISSUE THREAD

**Issue by Tinhone** [penguin-statistics/frontend-v2#556]
尝试连接 `penguin-stats.cn` 后返回：`{"msg":"connection reset by peer","code":"50303005","id":"89213d377e8e1d31338ad7e332f45def"}`

浏览器：Firefox V88.0

状态码：503 Service Unavailable

响应头，抹去了时间：
<html><body>

占位符 | 也是占位符
-- | --
X-Firefox-Spdy | h2
content-length | 92
content-type | application/json
server | marco/2.19
strict-transport-security | max-age=31536000; includeSubDomains; preload
via | S.mix-js-taz1-221, T.221.D, V.mix-js-taz1-218, T.205.D, M.cmn-sc-ctu8-205
x-error-code | 50303005
x-request-id | 89213d377e8e1d31338ad7e332f45def
x-source | SC/error

</body>
</html>

换成 Edge V111.0.1661.62 之后是这样：
![图片](https://github.com/penguin-statistics/frontend-v2/assets/81268244/7ce9dec9-cee0-40eb-b7a0-1df9db4ccf42)

但与`penguin-stats.io`的连接是正常的

不知道是什么情况，因此开个 issue 询问一下大佬们😵

**Comment by DrSenkin** [comment]
ios端也是类似情况，但是无法同步的东西不止前端配置和物品数据，但是我EDGE 114.0.1823.58 （64位）打开没问题
可能cn的出问题了？且ios的问题更复杂，详见#561

**Comment by GalvinGao** [comment]
感谢汇报，问题现在应该已经被修复。原因是上游所使用的 fiber 库在更新后产生了功能劣化。我们已对对应的 CORS 请求加入测试集，以期望此后防止此类问题再次出现。
