### ISSUE TITLE
Failed to sign in automatically after reporting

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#56]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

### URL
`https://penguin-stats.io/report`

### Steps to reproduce
1. Report a drop record as an anonymous user (without userID)
2. Fail to sign in after reporting

### What is expected?
The response will set userID in cookies if the submit is successful. We should use it to sign in.

### What is actually happening?
N/A

**Comment by GalvinGao** [comment]
We should check if `Set-Cookie` was defined in the response header. If we are not being able to check it via `AxiosResponse` then we may use some kind of watcher to watch the value of `window.cookie` and act when necessary.
