### ISSUE TITLE
[Bug]: Side Story MN-2 "Extra" Items have incorrect limit

### ISSUE THREAD

**Issue by Engstory** [penguin-statistics/frontend-v2#560]
### 环境 // Environment

操作系统 / Operating System: Windows 11 using Bluestacks 5.11.56.1002 P64 emulator
浏览器名称 / Browser Name: Google Chrome
浏览器版本 / Browser Version: Version 114.0.5735.199

### 出现此问题的页面链接 // URL of the page that the problem occurred in

https://penguin-stats.io/report/stage/permanent_sidestory_6_zone1/act13d5_02_perm

## 您都做了哪些事情/我们如何才能复现这个问题呢？ / What steps did you take to reproduce this problem?
[GLOBAL VER]
1. Played Side Story MN-2 mission;
2. The drops are LMD, one type of Regular Drops, and two types of Extra drops;
3. Went to the URL above to report drops, but error messages poped up as provided in the additional info section.

## 期望的结果 / What should have happened?
1. All drops should be reported no problem

## 实际的结果 / What actually happened?
1. Error message popped up saying the maximum items in "Extra" is incorrect

## 额外的信息 / Any additional information?
1. Penguin ID: #66794339, SERVER US
2. Error messages:
![image](https://github.com/penguin-statistics/frontend-v2/assets/99150304/e178c725-5f02-42ae-9a25-f5c022389f6b)
![image](https://github.com/penguin-statistics/frontend-v2/assets/99150304/0510b421-1a97-46a0-8b5a-97479a799012)

3. Drop Screenshots:
![Screenshot_2023 06 29_01 14 12 281](https://github.com/penguin-statistics/frontend-v2/assets/99150304/a12f5fc6-06db-48fb-a1b5-f34b2d9bbe09)
![Screenshot_2023 06 29_01 17 27 176](https://github.com/penguin-statistics/frontend-v2/assets/99150304/72901821-47a3-47c9-bde5-fb4dca94c648)
![Screenshot_2023 06 29_01 20 52 357](https://github.com/penguin-statistics/frontend-v2/assets/99150304/b4602a30-6ee6-487e-9cc1-b1feed92398f)
![Screenshot_2023 06 29_01 23 45 322](https://github.com/penguin-statistics/frontend-v2/assets/99150304/0f493800-4d01-4e04-a76a-3d70d4d12a4d)

**Comment by AlvISsReimu** [comment]
fixed, thanks for raising this issue!
