### ISSUE TITLE
[Bug]: IOS App 无法连接并同步数据，切换主题有机会导致界面语言变为英文（ios默认语言为中文）

### ISSUE THREAD

**Issue by DrSenkin** [penguin-statistics/frontend-v2#561]
### 环境 // Environment

操作系统 / Operating System: ios 16.5.1
软件版本 / App Version: 3.13.0

软件主题 / App Theme: 我们同类

### 出现此问题的页面链接 // URL of the page that the problem occurred in

https://penguin-stats.cn/

## 您都做了哪些事情/我们如何才能复现这个问题呢？ / What steps did you take to reproduce this problem?
1.正常打开App
2.报错 （连接异常）
3.如果切换主题到默认主题，有时则软件语言则会变为英语，虽系统默认语言（汉语）应该与软件语言保持一统。在改情况下，就算切换到其他主题依旧是英语，重启后则恢复正常，该问题可复现，在多台ios设备尝试了，虽随机性很大。
![IMG_4948](https://github.com/penguin-statistics/frontend-v2/assets/130391534/d2720eb1-68cc-4f46-bd70-a134008ad2df)

## 期望的结果 / What should have happened?
1.同步资源，正常连接
2.中文界面

## 实际的结果 / What actually happened?
1.连接异常，前端配置，物品数据，作战元数据，全平台掉落数据，汇报历史数据，全站概览数据都无法同步。
2.有时会以英文界面显示

## 额外的信息 / Any additional information?
1. 网站版本（.cn)正常运转，但是软件近期都如此报错

![IMG_4947](https://github.com/penguin-statistics/frontend-v2/assets/130391534/f24c1511-1d4d-4992-a72c-a77de412e680)

**Comment by DrSenkin** [comment]
补充：在大陆会出现以上问题，在香港则不会，估计是网站本身的问题

**Comment by GalvinGao** [comment]
App 的相关问题已被修复；无法切换语言的问题我们这两天看下，也有其他用户报告

**Comment by SunshineboyZj** [comment]
我也遇到了类似问题，（手机、PC）始终是英文界面，重启浏览器和清除数据都无法解决（.cn网站，国服服务器，语言中文）

**Comment by GalvinGao** [comment]
感谢您汇报此问题。我们已于 7.6 21:54 发布的 v3.13.6 版本中修复此问题。经观察，发布的新版本没有再出现此问题。

问题根因确实为处理语言文件 CDN 服务拉取失败时的逻辑错误。具体的修复可见 https://github.com/penguin-statistics/frontend-v2/commit/0b6dc52dba4031d8104b4b1b41dd57a0f5bb379d。

此后我们将尽力在上线新版本前提供更多测试。很抱歉对各位带来不便！
