### ISSUE TITLE
[Bug]: 网站在反复多次切换语言时概率不显示翻译的字符串而直接显示原始的键

### ISSUE THREAD

**Issue by NishikiAsumi0** [penguin-statistics/frontend-v2#564]
### 环境 // Environment

操作系统 / Operating System:  Windows 11 专业版 22H2 22621.1848
浏览器名称 / Browser Name: Google Chrome
浏览器版本 / Browser Version:  114.0.5735.199

### 出现此问题的页面链接 // URL of the page that the problem occurred in

https://penguin-stats.cn/; https://penguin-stats.io/

## 您都做了哪些事情/我们如何才能复现这个问题呢？ / What steps did you take to reproduce this problem?
打开网站时同时伴有 #563 的问题，试图调整语言的时候出现该问题。
随机多次切换语言约四到五次时就会出现，目前看来与切换顺序、次数、最后切换到的语言均无关

## 期望的结果 / What should have happened?
显示正确的对应的翻译

## 实际的结果 / What actually happened?
![image](https://github.com/penguin-statistics/frontend-v2/assets/58659973/8b7857cc-8fdb-4716-9661-b6fca0d71116)

## 额外的信息 / Any additional information?
1.

**Comment by GalvinGao** [comment]
感谢您汇报此问题。我们已于 7.6 21:54 发布的 v3.13.6 版本中修复此问题。经观察，发布的新版本没有再出现此问题。

问题根因确实为处理语言文件 CDN 服务拉取失败时的逻辑错误。具体的修复可见 https://github.com/penguin-statistics/frontend-v2/commit/0b6dc52dba4031d8104b4b1b41dd57a0f5bb379d 。

此后我们将尽力在上线新版本前提供更多测试。很抱歉对您带来不便！
