### ISSUE TITLE
[Bug]: 国内站寄了

### ISSUE THREAD

**Issue by TimCrownie** [penguin-statistics/frontend-v2#577]
### 环境 // Environment

操作系统 / Operating System: Windows 10 22H2
浏览器名称 / Browser Name: Google Chrome
浏览器版本 / Browser Version: 126.0.6478.128

### 出现此问题的页面链接 // URL of the page that the problem occurred in

https://penguin-stats.cn/

## 您都做了哪些事情/我们如何才能复现这个问题呢？ / What steps did you take to reproduce this problem?
1. 访问国内站(https://penguin-stats.cn/)时
2. 使用MAA的自带上报掉落功能时
3.

## 期望的结果 / What should have happened?
1. 能够正常访问

## 实际的结果 / What actually happened?
1. 无法访问，显示如下内容
![image](https://github.com/user-attachments/assets/4242565a-dc61-4e8e-9f85-34c4dca76033)
2. MAA显示“上报失败，放弃上传企鹅物流”_（插一嘴 好孩子不要学我半夜不睡觉挂1-7）_
![image](https://github.com/user-attachments/assets/229c0db5-48fb-4a58-b381-b3a23a55e884)

## 额外的信息 / Any additional information?
1. N/A

**Comment by hyb-oyqq** [comment]
已经恢复啦，可以关掉咯

**Comment by TimCrownie** [comment]
> 已经恢复啦，可以关掉咯

好好好（

**Comment by TimCrownie** [comment]
> 已经恢复啦，可以关掉咯

然后又寄了，怀疑国内站的运营费用真的是吸血（

**Comment by TimCrownie** [comment]
不对 这应该不需要重开issue
