### ISSUE TITLE
Change the text on the lower right corner

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#6]
### What problem does this feature solve?
I'm feeling like using "企鹅物流数据统计" is better than "企鹅物流".  After all, we are not Penguin Logistics lol

### What does the proposed API look like?
N/A

**Comment by GalvinGao** [comment]
We will use `企鹅物流数据统计` as the Chinese project name, and `Penguin Statistics` as the English project name, right?

**Comment by AlvISsReimu** [comment]
> So we are gonna use `企鹅物流数据统计` as the Chinese project name, and `Penguin Statistics` as the English project name?

Yes, that's my initial idea. Does this sound good?

**Comment by GalvinGao** [comment]
Ok gotcha. I'll just use that.
