### ISSUE TITLE
Scroll to the top of page after routing

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#60]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

### URL
`https://penguin-stats.io`

### Steps to reproduce
1. Visit homepage under mobile view, scroll to the bottom 
2. Open the menu, choose to see results by stage
3. After routing, we are still at the bottom of the page

### What is expected?
We want instant scrolling to the top instead of smooth scrolling.

### What is actually happening?
N/A

**Comment by GalvinGao** [comment]
The one can utilize `window.scrollTo(0, 0)`. ps: the reason im not solving this is because im sleepy 💤
