### ISSUE TITLE
Google Analytics Implementation

### ISSUE THREAD

**Issue by GalvinGao** [penguin-statistics/frontend-v2#92]
### What problem does this feature solve?
We need to analyze our user (and their interactions)

### What does the proposed API look like?
User interaction is well-tracked

**Comment by AsahiLuna** [comment]
We should remind user about Google Analytics information, maybe we can add a card to the home page?

**Comment by AsahiLuna** [comment]
Are we should isolate the google analytics method to a js lib?

Then we can unify the google analytics data in this lib, and easy to use everywhere.
